### PR TITLE
Explicitly request all required post status

### LINKED ISSUE #940: Trashed pages missing on self-hosted sites w/o Jetpack
The `TRASH`ed pages are not downloaded from self-hosted sites without Jetpack.

To test:
1. Open a self-hosted site without Jetpack
2. Go to Site pages
3. Move a page to trash
4. Go to the Trashed tab
5. Notice the list is empty

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #940. 

To test this, test the #wordpress-mobile/WordPress-Android/pull/8462 please.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Just for the record, it's worth mentioning that this request might fail if the user has altered the possible post statuses in their site. It kind of makes sense to still have it, because at the worst, it should just return an empty result. However, the "correct" way to handle this might be to fetch the possible post statuses from remote first and then use those statuses to show various filters for xml-rpc sites.

/cc @aerych

**Comment by aerych** [comment]
I'm confused.  My fluxc is really rusty so I'm probably missing something, but it looks like we are requesting the possible status from the remote first?  In what way might it fail?

**Comment by aerych** [comment]
Fwiw, given just how customizable WP can be there will always be things we don't support.  I'm cool with core feature coverage.  If we later learn there's a popular plugin modifying things we could iterate.

**Comment by oguzkocer** [comment]
> I'm confused. My fluxc is really rusty so I'm probably missing something, but it looks like we are requesting the possible status from the remote first? In what way might it fail?

`PostStatus` is just an enum not a request from remote afaik: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/post/PostStatus.java

> Fwiw, given just how customizable WP can be there will always be things we don't support. I'm cool with core feature coverage. If we later learn there's a popular plugin modifying things we could iterate.

As long as we are aware of the issue, that's fine by me.

**Pull request closed without merging**
