### PR TITLE
[Detekt Baseline Warnings] Example Module - Resolve/Suppress Other Warnings

### LINKED ISSUE #2487: Resolve/Suppress Detekt Baseline Warnings - Example Module
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `example` module.

Number of Warnings: `176`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2502
    - style (`87`) ✅
        1. DataClassShouldBeImmutable (`4`) ✅
        4. MagicNumber (`6`) ✅
        5. MaxLineLength (`3`) ✅
        6. ReturnCount (`2`) ✅
        7. UnnecessaryAbstractClass (`3`) ✅
        8. UnusedPrivateMember (`11`) ✅
        9. UseArrayLiteralsInAnnotations (`1`) ✅
        10. UseCheckOrError (`6`) ✅
        11. UtilityClassWithPublicConstructor (`1`) ✅
        12. WildcardImport (`49`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2504
    - complexity (`63`) ✅
        1. ComplexCondition (`2`) ✅
        2. ComplexMethod (`16`) ✅
        3. LargeClass (`7`) ✅
        4. LongMethod (`36`) ✅
        6. NestedBlockDepth (`2`) ✅
    - naming (`1`) ✅
        1. TopLevelPropertyNaming (`1`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2507
    - coroutines (`9`) ✅
        1. GlobalCoroutineUsage (`9`) ✅
    - empty-blocks (`3`) ✅
        1. EmptyFunctionBlock (`3`) ✅
    - exceptions (`13`) ⚙️
        1. PrintStackTrace (`2`) ✅
        2. SwallowedException (`2`) ✅
        3. TooGenericExceptionCaught (`9`) ✅
    - performance (`1`) ✅
        1. SpreadOperator (`1`) ✅

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2479
Partially Closes: #2487

This PR resolves/suppresses all `other` related warnings for the `example` module:

- `9` x coroutines
    1. `9` x GlobalCoroutineUsage (Resolve: 3ce4307e56489866d691d7e556b14d4f11eb36b9 + Suppress: 3b22d4909cd1895c72fb0de9d92bd84b47ff94c6)
- `3` x empty-blocks
    1. `3` x EmptyFunctionBlock (Resolve: d7b19ad99cc23f8a52be01c09a20132c01f6495f)
- `13` x exceptions
    1. `2` x PrintStackTrace (Suppress: d13b29b1dbdbdb3703749901388088765b283b1e)
    2. `2` x SwallowedException (Suppress: 4ff7fa7b9b615a1776b1a572589cfc3ef67a2a76)
    3. `9` x TooGenericExceptionCaught (Suppress: eb9baf4246085d1425acb5ffa17ac3781590812e)
- `1` x performance
    1. `1` x SpreadOperator (Suppress: f8def6d8a5dbdec3b17129cd8f191fe9f776e3ea)

PS.1: I am randomly adding an engineer from either the WPAndroid or WCAndroid team as the main reviewer, that is, in addition to the @wordpress-mobile/owl-team team itself, since I just want someone from these teams to sign-off on that change as well (or additionally to the 🦉 team).

PS.2: I recommend reviewing this PR commit-by-commit.

-----

Also, in addition to the above, with this PR and by having all baseline warnings now resolved/suppress, the baseline for Detekt is no longer needed and as such completely removed from this repo (see 952c5e6ff2f15999010575b1c8bb734eeb00338e).

-----

To test:

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough (especially the `detekt` check).
- However, if you really want to be thorough, you could smoke test the `example` and/or the `WPAndroid/WCAndroid` apps to verify that everything works as expected.

PS: Please ignore the failing `connected-tests` check as they are unrelated to this PR. This check has been failing consistency for some time now due to tests being flaky or needing to be updated/fixed.

Merge instructions:

- [x] Wait for #2504 to be approved and merged to `trunk`.
- [x] Make sure this PR's base is automatically updated to `trunk`.
- [x] Update PR with latest `trunk`.
- [x] Remove `[Status] Not Ready for Merge` label.
- [x] Merge PR to `trunk`.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @AjeshRPai , how are you doing today! ☀️

Apologies for the extra ping, I just wanted you to know that I am on AFK from next week, and for a total of 3 weeks. As such, it would be great if we could wrap-up this PR today.

However, if you won't have the capacity to do the review today, not to worry, I would just appreciate if you take this over afterwards, in my absence, and:
- Apply any changes that you feel is necessary, that is, after you doing the code review and in case you identify any.
- Merge it yourself as soon as you feel it is ready, it is totally okay, and you don't have to wait for me to do that.

Thank you so much for your help here! 🥇 🙇 🌟

PS: This PR looks fancy, but it is actually very simple, small and straightforward. It shouldn't take you more than few minutes to review it. Especially if you do it commit-by-commit, the review will become so much more easier on you.

**Review by AjeshRPai — APPROVED** [review]
@ParaskP7 Sorry for the late reply. I have reviewed the PR commit-by-commit and everything looks good to me other than the failing connected tests. I believe this PR is not the cause of the failure of the connected tests, hence am approving the PR. 👍🏼 

👏🏼 I really appreciate your commit message practice. Every commit has the link to the detekt rule which helps me in review. 🙌🏼 . Also, appreciate the commit message with relevant links for the spread operator. Really helpful.

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

Thank you so much for the review and testing! 🥇 🙇 🌟

PS: I am now going to resolve the `config/detekt/baseline.xml` conflict with an additional, by removing Detekt's baseline configuration altogether. I'll let you know in 5' mins about that for a final review before me merging it to `trunk`. Is that okay? 🙏

**Comment by AjeshRPai** [comment]
>I'll let you know in 5' mins about that for a final review before me merging it to trunk. Is that okay? 🙏

Yup, that works for me. 👍🏼

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

> PS: I am now going to resolve the config/detekt/baseline.xml conflict with an additional, by removing Detekt's baseline configuration altogether. I'll let you know in 5' mins about that for a final review before me merging it to trunk. Is that okay? 🙏

This is now done, I resolved the conflict and [removed the baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2507/commits/952c5e6ff2f15999010575b1c8bb734eeb00338e), can you please take one last look at it? 🙇

**Comment by AjeshRPai** [comment]
@ParaskP7 Everything LGTM. I have taken a pull and ran the example on local. 👍🏼 . I can also see that the detekt CI also passed successfully. So all is good from my side. Please feel free to merge after all the CI checks are passed. Have a happy Friday and AFK.

**Comment by ParaskP7** [comment]
👋 @AjeshRPai !

Great! 🎉

Once more thank you so very much for your timely review and for making sure that everything is working as expected, you rock! ❤️ 🪨 🥇 

PS: Also, I am humbled by your kind words on the commits and their structure, I am glad they helped you review this PR more effectively. 🙇 

> Have a happy Friday and AFK.

Thank YOU! 🍹 And happy Friday to you too, weekend is almost there for you!! ⌛

**Pull request merged**
