### PR TITLE
Media local site id

### LINKED ISSUE #303: MediaStore: SQL queries must be done using the local site id, not the site id
SiteId represents the remote id of jetpack and wpcom sites, but it's not set on self hosted sites. Only the local site id can be used to identify sites in the DB.

So we must add a new localSiteId (int) field to the MediaModel and then use it everywhere for SQL queries (insert and select).

### PR DESCRIPTION
**Pull request by oguzkocer**
Closes #303. This PR removes the `siteId` property from `MediaModel` and adds `localSiteId` instead. A lot of changes needed to be made to reflect these changes. However, changes are pretty straightforward. I tried to use `local` versions of variable names where I can, so it's a bit more obvious.

There is a failing test in this PR `MediaStoreTest.testGetLocalSiteMedia` however it's already failing in the `issue/missing-integration-functionality` branch, so it should be fine.

This also solves the fetching self-hosted media issue mentioned in the wpandroid integration branch.

/cc @maxme

### CODE REVIEW

**Comment by maxme** [comment]
I was a bit hesitant to remove the remote site id. We don't use it right now but I thought we could reuse it in media `push` actions by passing a single MediaModel instead of passing a MediaModel plus a SiteModel - but we're not going to drop support for self hosted sites, and we need more than just a remote id to make the network call on these sites.

**Comment by maxme** [comment]
> There is a failing test in this PR MediaStoreTest.testGetLocalSiteMedia however it's already failing in the issue/missing-integration-functionality branch, so it should be fine.

I merged `issue/missing-integration-functionality` back in this and the unit tests pass.

**Comment by maxme** [comment]
Connected tests are not building (ReleaseStack_MediaTestWPCom.java and ReleaseStack_MediaTestXMLRPC.java)

**Comment by oguzkocer** [comment]
> I was a bit hesitant to remove the remote site id. We don't use it right now but I thought we could reuse it in media `push` actions by passing a single MediaModel instead of passing a MediaModel plus a SiteModel - but we're not going to drop support for self hosted sites, and we need more than just a remote id to make the network call on these sites.

That makes sense. I am only a bit hesitant for it to be confusing for the devs though.

**Comment by oguzkocer** [comment]
@maxme Fixed the build errors, as well as catching a bug about upload media in xmlrpc. We were never setting the `siteId` for the media, so it'd always be zero and the tests were passing because `sSite` in the xmlrpc tests had 0 as the `siteId`. This is somewhat expected since `siteId` is supposed to be for .com, but other media actions were setting it.

Anyway, all should be resolved now.

**Comment by maxme** [comment]
Note: this one ready to merge after https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/305

**Pull request merged**
