### PR TITLE
Issue/migrate to paging 3

### LINKED ISSUE #14860: Post list fails to refresh or crashes the app when you scroll quickly
### Expected behavior
The posts list refreshes in all cases

### Actual behavior

The post list fails to refresh when you scroll down too quickly (sometimes causing a crash) or after cleaning the cache

<details>
 <summary>Unable to refresh</summary>

https://user-images.githubusercontent.com/304044/122415971-0372e100-cf91-11eb-8c51-00b0e55de301.mp4
</details>

<details>
 <summary>Crash log</summary>

```
    java.lang.IllegalArgumentException: Illegal start(60) or end(80) position for totalSize(62)
        at org.wordpress.android.fluxc.model.list.datasource.InternalPagedListDataSource.getItemIds(InternalPagedListDataSource.kt:61)
        at org.wordpress.android.fluxc.model.list.datasource.InternalPagedListDataSource.getItemsInRange(InternalPagedListDataSource.kt:51)
        at org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource.loadRangeInternal(PagedListFactory.kt:58)
        at org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource.loadRange(PagedListFactory.kt:49)
        at androidx.paging.PositionalDataSource.loadRange(PositionalDataSource.kt:430)
        at androidx.paging.PositionalDataSource.load$paging_common(PositionalDataSource.kt:348)
        at androidx.paging.LegacyPagingSource$load$2.invokeSuspend(LegacyPagingSource.kt:116)
        at androidx.paging.LegacyPagingSource$load$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at androidx.paging.LegacyPagingSource.load(LegacyPagingSource.kt:115)
        at androidx.paging.LegacyPageFetcher$scheduleLoad$1.invokeSuspend(LegacyPageFetcher.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```
</details>

This seems to be new to `17.6` [according to Sentry](https://sentry.io/share/issue/09d3b8128d0e448abd3e8c3be693bcd9/)

#### By scrolling
1. Go to the post list and scroll down quickly
2. Notice that the list fails to refresh **or the app crashes**
3. Notice that the list is empty (and it shouldn't)
4. Try to refresh by pulling down
5. Notice that the screen does not refresh
6. Go back to the My Sites screen
7. Open the post list again
8. Notice the the posts are there

#### By clearing the cache (not reproduced consistently)
1. Go to the app settings and clear the cache and stored data
2. Open the app and login again
3. Go to the post list
4. Notice that the list is empty (and it shouldn't)
5. Try to refresh by pulling down
6. Notice that the screen does not refresh
7. Go back to the My Sites screen
8. Open the post list again
9. Notice the the posts are there

### PR DESCRIPTION
**Pull request by khaykov**
This PR adds support for Paging 3, and fixes [issues](https://github.com/wordpress-mobile/WordPress-Android/issues/14860) with using legacy Paging 2 functionality.

You can test it with [this](https://github.com/wordpress-mobile/WordPress-Android/pull/14977) wpandroid PR.

I found out that all kinds of issues happen when you repeatedly invalidate DataSource, for example, when your list loads items individually, and after each load, the DataSource is invalidated.

I fixed them by debouncing invalidate events. From experimenting, 750ms delay was a sweet spot. Open to alter

Just in case, I added a check to `loadRange` to make sure that the request does not exceed the total size of the dataset.

Also, I extracted `computeInitialLoadPosition` and `computeInitialLoadSize` into PagedListPositionalDataSource, because in Paging 3 they became restricted to the library, despite being static companion methods, that are still documented as public 🤷 

@wzieba Would yo mind checking if the List functionality in woo is working as expected with this branch?

### CODE REVIEW

**Review by oguzkocer — CHANGES_REQUESTED** [review]
> I fixed them by debouncing invalidate events. From experimenting, 750ms delay was a sweet spot. Open to alter

I saw this PR review request after I posted a comment on today's retrospective post and I'd like to reiterate my point here. I think this ^ treats a symptom and not the root cause. I feel it's a big red flag to fiddle with throttling numbers, especially around `750ms` 😱 

I've only briefly looked at the paging 3 documentation, but it looks like the underlying structure changed quite a bit and I think it's very important for us to understand the changes and how it'll impact the existing implementation before rushing to a version upgrade.

I am going to mark this as `Request changes` for now until I can fully read the documentation and review this PR because once we do this upgrade it's going to be very hard to turn back. I am worried that, we will find ourselves fixing issues as they get reported instead of handling it correctly from the start.

**Comment by oguzkocer** [comment]
@khaykov I've updated most of the ListStore stack to use the new API and besides a few positional issues, it looks promising. No issues with invalidation either.

I'll try to get this done early next week.

**Comment by khaykov** [comment]
@oguzkocer Thank you for looking into it. It's my first time even looking at Lists, so as said this fix is indeed for a symptom and not the root cause. From what I cant tell, Paging 3 is way simpler, especially when paired with Room, and my intention was to use it without changing `ListStore`, since I feel that they are very different conceptually.

Also, if the migration will prove difficult, we are looking into not using Paging 3 (just in case).

**Comment by oguzkocer** [comment]
@khaykov Migration is definitely not straightforward, but if I can get it done in a reasonable time, I think it's worth it. I'll look into converting `ListItemModel` to use Room instead since we started using it elsewhere. That might actually make things easier for us 🤔 

Once that is done ^, I'd love to chat about your project and whether ListStore can match your needs.

**Comment by wzieba** [comment]
I'm also concerned about the timing-based solution - if it's okay @khaykov , I'll review & test PR with Woo app as soon as this change will be approved. I'm also in favour of migrating to Paging 3 even it'll be difficult - I'm worried that a decision to stick to the Paging 2  (deprecated sooner or later) might be a risky move as it can (will?) revenge on us in the future.

**Comment by khaykov** [comment]
@oguzkocer Ready for another round. I left some explanation on slack, but copying it here just in case:

> Paging 2 that runs alongside Paging 3 (without migration) can sometimes encounter an issue where the DataSource can get stuck in an invalidated state, and create() will not be called from the factory. The assumption is that the issue is with threading inside the library, between fetchDispatcher (running on BG thread by default) and notifyDispatcher that runs on the Main thread. I looked through the Paging source, and there are some context switches and communication between main and DB threads. Probably something is not thread-safe, and at some point, some sort of deadlock is happening. My solution is to run fetchDispatcher on the same thread as notifyDispatcher (main), but only to sequence requests, and avoid context switching. Actual loading in DataSource will still happen on the BG thread.

**Comment by oguzkocer** [comment]
I've left some feedback about this in `#liststore-paging-v3-upgrade` Slack channel. I typically prefer Github discussions so it's all out in public, but for this particular issue I think it'd be good to use Slack to move faster. We can add some updates to the Github PR/issue along the way to keep others updated.

Everyone at Automattic is welcome to join the Slack channel and if anyone else wants to join in, please ping me in this PR and we'll sort it out. Thanks!

**Comment by oguzkocer** [comment]
@khaykov Since this work is currently on hold, could we close the PR and re-open it if/when it's necessary?

**Comment by khaykov** [comment]
@oguzkocer Sure, sounds good to me 👍

**Pull request closed without merging**
