### PR TITLE
[Build] Enable Non-Transitive Resources

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR is a prerequisite for the `Gradle 8.1.1 & AGP 8.0.2 Upgrade for WPAndroid, WCAndroid & Related Libs` project.

Platform Request: `pdnsEh-13V-p2`
Project Thread: `paaHJt-57Z-p2`

-----

This PR enables non-transitive resources (`android.nonTransitiveRClass`) for the project.

FYI: This behavior becomes the default in AGP `8.0` and higher. As such, this becomes a prerequisite for the AGP `8.0.2` upgrade, that is of course, unless `android.nonTransitiveRClass` is explicitly set to `false`.

PS: This PR also disables Jetifier (87139a60e0528b3e7d18ca39beff64b07cee0968), something that was [already discussed](https://github.com/wordpress-mobile/WordPress-Android/pull/15675#issuecomment-1057840724) back then (1,5 years ago), but we never got around to applying and testing this change.

-----

## To test:

1. Verify that all the CI checks are successful.
2. Smoke test the app.
3. Also, because of this (87139a60e0528b3e7d18ca39beff64b07cee0968) and this (251b1a5cdbf4caf76171b529db5c79bb67c70b50) changes, just to be on the safe side, you could quickly smoke test both, the WPAndroid and WCAndroid apps, and verify that everything is working as expected.

FYI: Due to the above 87139a60e0528b3e7d18ca39beff64b07cee0968 and 251b1a5cdbf4caf76171b529db5c79bb67c70b50 changes, I am also considering updating the [wellsql](https://github.com/wordpress-mobile/wellsql) project and level-it-up with all other repos that we are currently supporting. Maybe then, we can drop the `com.android.support` group dependency exclusion from the `wellsql` dependency altogether, and this way, to avoid any future bottlenecks when working with [wellsql](https://github.com/wordpress-mobile/wellsql). Wdyt @oguzkocer ?

-----

Please also notice this 8fff0be773d82b938d46d00d08b7eb476720ffcf and its description. This commit doesn't updates the encrypted `gradle.properties.enc` file as it seems that this kind of encrypted `gradle.properties` file isn't available for this project.

Can you please confirm the above? 🤔 

And if that's the case, let's take this opportunity to remove any such encryption related functionality from this repo.

### CODE REVIEW

**Comment by ParaskP7** [comment]
> FYI: Due to the above https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/87139a60e0528b3e7d18ca39beff64b07cee0968 and https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/251b1a5cdbf4caf76171b529db5c79bb67c70b50 changes, I am also considering updating the [wellsql](https://github.com/wordpress-mobile/wellsql) project and level-it-up with all other repos that we are currently supporting. Maybe then, we can drop the com.android.support group dependency exclusion from the wellsql dependency altogether, and this way, to avoid any future bottlenecks when working with [wellsql](https://github.com/wordpress-mobile/wellsql). Wdyt @oguzkocer ?

**UPDATE**: I went ahead and created this `wellsql` related PR anyway, I think it is worth the trouble, that is, for the amount of time it took me to deal with it today: [[Build] Update Gradle to 7.4.2 & AGP to 7.2.1 #24](https://github.com/wordpress-mobile/wellsql/pull/24) 😊

**Review by oguzkocer — COMMENTED** [review]
> Please also notice this https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/8fff0be773d82b938d46d00d08b7eb476720ffcf and its description. This commit doesn't updates the encrypted gradle.properties.enc file as it seems that this kind of encrypted gradle.properties file isn't available for this project.

This library, [similar to `stories-android`](https://github.com/Automattic/stories-android/pull/736#pullrequestreview-1513543721), is using the [configure Gradle plugin](https://github.com/Automattic/configure/). You should be able to update the encrypted file with `./gradlew updateConfiguration`. Without the secrets, the instrumented tests wouldn't work.

> UPDATE: I went ahead and created this wellsql related PR anyway, I think it is worth the trouble, that is, for the amount of time it took me to deal with it today: https://github.com/wordpress-mobile/wellsql/pull/24 😊

Thank you for taking care of this! I've approved that PR. If all the work for that repo is done, could you merge the PR, tag it and update this PR with the new version? I assume we'll no longer need to exclude `com.android.support` with that update. 🤞 I would have been happy to take care of all this, but didn't want to intervene without your explicit approval 😅

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

> This library, https://github.com/Automattic/stories-android/pull/736#pullrequestreview-1513543721, is using the [configure Gradle plugin](https://github.com/Automattic/configure/). You should be able to update the encrypted file with ./gradlew updateConfiguration. Without the secrets, the instrumented tests wouldn't work.

Ah, probably I didn't make myself clear, apologies Oguz. 😊 

What I was trying to say is that there is no `gradle.properties` file in secrets for FluxC, just like it does exist for both, WPAndroid and WCAndroid. However, I agree, the instrumented test related `api.properties`, `tests.properties` and `test.properties-extra` do exist, I am not suggesting we remove those. I am only suggesting to delete the `gradle.properties.enc` file as it is no longer required, I think, please correct me again if I am wrong. 🤷

Am I am missing something obvious... 😊

> Thank you for taking care of this! I've approved that PR. If all the work for that repo is done, could you merge the PR, tag it and update this PR with the new version? I assume we'll no longer need to exclude com.android.support with that update. 🤞 I would have been happy to take care of all this, but didn't want to intervene without your explicit approval 😅

Done: f9c899d5769a1d292059c3f36a78444df5728d4e

FYI: Updating `wellsql` to [1.8.0](https://github.com/wordpress-mobile/wellsql/releases/tag/1.8.0), indeed, removes the need to exclude `com.android.support`.

**Comment by oguzkocer** [comment]
> What I was trying to say is that there is no gradle.properties file in secrets for FluxC, just like it does exist for both, WPAndroid and WCAndroid. However, I agree, the instrumented test related api.properties, tests.properties and test.properties-extra do exist, I am not suggesting we remove those. I am only suggesting to delete the gradle.properties.enc file as it is no longer required, I think, please correct me again if I am wrong. 🤷

Ah, sorry about that. Yes, I think we can remove the unused encrypted file.

**Comment by ParaskP7** [comment]
> Yes, I think we can remove the unused encrypted file.

Awesome, thanks the confirmation on that @oguzkocer ! 🙇

Done: 618bce06a2b3fb4837f45efdae10410354f9f89b

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

FYI: Catalog was updated to latest [1.11.0](https://github.com/Automattic/android-dependency-catalog/releases/tag/1.11.0), and with that, this PR is ready for another review: e2ae59ccf3a1e522a28a70f5710621c51d324c37

**Review by oguzkocer — APPROVED** [review]
Thanks for taking care of this @ParaskP7! I've tested it with WPAndroid and it seems to be working as expected.

I am going to merge this PR so that I can include it in the upcoming code freeze, so that these changes are tested before we upgrade AGP.

Also note that I couldn't directly test it with WCAndroid because this branch is behind `trunk` and there is a breaking change. However, I'll test it with the merge commit afterwards and make sure to follow up if I find any issues with it.

**Comment by ParaskP7** [comment]
Awesome, thank you for reviewing, testing and merging this @oguzkocer , you rock! 🙇 ❤️ 🚀

> Also note that I couldn't directly test it with WCAndroid because this branch is behind trunk and there is a breaking change. However, I'll test it with the merge commit afterwards and make sure to follow up if I find any issues with it.

Noted! 👍

**Pull request merged**
