### PR TITLE
[Detekt Baseline Warnings] Example Module - Resolve/Suppress Complexity & Naming Warnings

### LINKED ISSUE #2487: Resolve/Suppress Detekt Baseline Warnings - Example Module
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `example` module.

Number of Warnings: `176`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2502
    - style (`87`) ✅
        1. DataClassShouldBeImmutable (`4`) ✅
        4. MagicNumber (`6`) ✅
        5. MaxLineLength (`3`) ✅
        6. ReturnCount (`2`) ✅
        7. UnnecessaryAbstractClass (`3`) ✅
        8. UnusedPrivateMember (`11`) ✅
        9. UseArrayLiteralsInAnnotations (`1`) ✅
        10. UseCheckOrError (`6`) ✅
        11. UtilityClassWithPublicConstructor (`1`) ✅
        12. WildcardImport (`49`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2504
    - complexity (`63`) ✅
        1. ComplexCondition (`2`) ✅
        2. ComplexMethod (`16`) ✅
        3. LargeClass (`7`) ✅
        4. LongMethod (`36`) ✅
        6. NestedBlockDepth (`2`) ✅
    - naming (`1`) ✅
        1. TopLevelPropertyNaming (`1`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2507
    - coroutines (`9`) ✅
        1. GlobalCoroutineUsage (`9`) ✅
    - empty-blocks (`3`) ✅
        1. EmptyFunctionBlock (`3`) ✅
    - exceptions (`13`) ⚙️
        1. PrintStackTrace (`2`) ✅
        2. SwallowedException (`2`) ✅
        3. TooGenericExceptionCaught (`9`) ✅
    - performance (`1`) ✅
        1. SpreadOperator (`1`) ✅

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2479
Partially Closes: #2487

This PR resolves/suppresses all `complexity` and `naming` related warnings for the `example` module:

- `63` x complexity
    1. `2` x ComplexCondition (Suppress: 98a29ae66613dd61ec42e33924b47ffaff21c44f)
    2. `16` x ComplexMethod (Suppress: + 342cd437de51f02f1bd73683dde916375167372e)
    3. `7` x LargeClass (Suppress: 3ea5eddb5eaf96c0455bed275c41b81ef2cd3474)
    4. `36` x LongMethod (Suppress: 764f10f9006878b277359ea09cd58987048b2efd)
    5. `2` x NestedBlockDepth (Resolve: 7c6782557efc7cea3dee856dfa24a9fdcd1cb9c3)
- `1` x naming
    1. `1` x TopLevelPropertyNaming (Suppress: 96f78fb4d9d1bf0bbdbc67acfb7299d8a256b833)

PS.1: I am randomly adding an engineer from either the WPAndroid or WCAndroid team as the main reviewer, that is, in addition to the @wordpress-mobile/owl-team team itself, since I just want someone from these teams to sign-off on that change as well (or additionally to the 🦉 team).

PS.2: I recommend reviewing this PR commit-by-commit.

-----

Also, in addition to the above, within this PR, this ff38205df7634461e3f6450bb1979bdd47dc4e25 commit reverts the previous 8a96a86fb723285d8a056231ebad6096231aadd9 commit, which changed the `level` field from `var` to `val`, and which is now breaking WPAndroid, but it is now easily solvable on the client side, thus it is now suppressed instead. See commit description for more details on that.

-----

To test:

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough (especially the `detekt` check).
- However, if you really want to be thorough, you could smoke test the `example` and/or the `WPAndroid/WCAndroid` apps to verify that everything works as expected.

PS: Please ignore the failing `connected-tests` check as they are unrelated to this PR. This check has been failing consistency for some time now due to tests being flaky or needing to be updated/fixed.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @hichamboushaba , how are you doing today! ☀️

Apologies for the extra ping, I just wanted you to know that I am on AFK from next week, and for a total of 3 weeks. As such, it would be great if we could wrap-up this PR today.

However, if you won't have the capacity to do the review today, not to worry, I would just appreciate if you take this over afterwards, in my absence, and:
- Apply any changes that you feel is necessary, that is, after you doing the code review and in case you identify any.
- Merge it yourself as soon as you feel it is ready, it is totally okay, and you don't have to wait for me to do that.

Thank you so much for your help here! 🥇 🙇 🌟

PS: This PR looks fancy, but it is actually very simple, small and straightforward. It shouldn't take you more than few minutes to review it. Especially if you do it commit-by-commit, the review will become so much more easier on you.

**Comment by hichamboushaba** [comment]
@ParaskP7 I'm planning to review this PR today, it'll be done in a couple of hours if that's OKay, sorry for the delay.

**Comment by ParaskP7** [comment]
> @ParaskP7 I'm planning to review this PR today, it'll be done in a couple of hours if that's OKay, sorry for the delay.

Awesome @hichamboushaba ! That is totally okay, even if you do at the end of your day, not to worry and no delays here, I was just making sure you are aware that I am going on AFK so that you know how to handle that afterwards if need be, thank you so much! 🙇

**Review by hichamboushaba — APPROVED** [review]
Looks good to me, I tested the build in WCAndroid, and everything looks fine.

Thanks for working on this @ParaskP7 💯

**Comment by ParaskP7** [comment]
👋 @hichamboushaba !

Thank you so much for the review and testing! 🥇 🙇 🌟

PS: And once more, my apologies for pushing you into reviewing this PR in an asap manner. 🙏

**Pull request merged**
