### PR TITLE
Update Dagger to 2.42

### PR DESCRIPTION
**Pull request by oguzkocer**
AGP `7.2.1` update results in a crash during lint due to a bug in Dagger which is addressed in `2.42`. This PR updates Dagger to `2.42` and targets the AGP update branch, so they can be shipped together.

### CODE REVIEW

**Review by ParaskP7 — CHANGES_REQUESTED** [review]
👋 @oguzkocer !

I reviewed and tested this PR, thank you for opening it! 🙏 

Comparing to the `trunk` version, while smoke testing this PR with the `example` app, I notice that it crashes when interacting with it on most of the UI buttons. For example, after building with this version, installing, opening the `FluxC Example` app, singing-in and clicking the `ACCOUNT` or any other non sign-in/out button, you will notice the below crash:

```
2022-07-04 11:47:19.247 1257-1257/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.fluxc.example, PID: 1257
    java.lang.IllegalStateException: ScrollView can host only one direct child
        at android.widget.ScrollView.addView(ScrollView.java:376)
        at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:833)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

For `AccountFragment`, this crash occurs during `onCreateView(...)` on line `33`.

I did a quick zoom-in into this problem and initially I didn't think it is `Dagger` specific. I thought it is must be specific to the `AGP` update to `7.2.1` that preceded the `Dagger` update so I reverted that to `7.1.1`. However, this didn't help, the crash kept persisting. Then, I reverted `Dagger` back to `2.29.1` and the crash was gone. So, it actually seems that this crash indeed is somehow related to the `Dagger` update to `2.42` and on something that got updated in-between the [2.29.1](https://github.com/google/dagger/releases/tag/dagger-2.29.1) (`10 Sep 2020`) and [2.42](https://github.com/google/dagger/releases/tag/dagger-2.42) (`10 May 2022`) versions (a diff of `1 Year, 8 Months`). 🤔 

Wdyt?

**Comment by oguzkocer** [comment]
@ParaskP7 Thank you for the review and sorry about missing this crash. I addressed it in fd3b2fef11f486a5e9be86edace0ee08059c4358 & 5777fbb364c1fff5db799a512dc7a85cc0d907b2.

I think this issue happened due to the transient dependency updates possibly related to `androidx.activity:activity:1.3.1` update from `1.1.0` or `androidx.fragment:fragment:1.3.6` update from `1.2.0`. This is one of the reasons why I believe it's good to be up to date on dependencies as much as we can, so at least dependency changes are transparent and doesn't require us to make these big jumps when we are forced to do.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Thank you so much for addressing this issue! ❤️ 🥇 🙇 

> I addressed it in https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/fd3b2fef11f486a5e9be86edace0ee08059c4358 & https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/5777fbb364c1fff5db799a512dc7a85cc0d907b2.

Nicely done! 💯 

> I think this issue happened due to the transient dependency updates possibly related to androidx.activity:activity:1.3.1 update from 1.1.0 or androidx.fragment:fragment:1.3.6 update from 1.2.0.

Ah, this is true, I totally missed checking or thinking about the dependency tree diff check, it seems that this might be it indeed. 👍 Now, I am wondering why I didn't see the dependency tree diff, and as I was scrolling through this PR, I kept wondering what I still don't see it, only to realize that we don't have this functionality on `FluxC` just yet, only on WPAndroid and WCAndroid... 😅 🤔 😅 

> This is one of the reasons why I believe it's good to be up to date on dependencies as much as we can, so at least dependency changes are transparent and doesn't require us to make these big jumps when we are forced to do.

💯 x 💯

**Review by ParaskP7 — APPROVED** [review]
I tested the update and can verify that it works now! 💯

**Pull request merged**
