### PR TITLE
Adds missing plugin properties

### PR DESCRIPTION
**Pull request by oguzkocer**
As discussed on Slack with @nbradbury we are adding all the fields we'll need for the plugin directory feature in advance. Since we already have a network call for fetching a single plugin, this change was a natural improvement on that even though the properties are not immediately utilized.

The only thing I am not completely sure about is how we extract the author name and author url fields from the response we get. There are some prettier ways to do this, but I think we need to be efficient there. I felt this was a good middle ground.

### CODE REVIEW

**Comment by nbradbury** [comment]
This looks good. I'm ready to :shipit: but first wanted to mention that as far as WPAndroid is concerned we don't need the separate author name & url fields, since the app ends up turning that into HTML anyway.

**Comment by oguzkocer** [comment]
> as far as WPAndroid is concerned we don't need the separate author name & url fields, since the app ends up turning that into HTML anyway

I wish I knew that before I spent so much time on finding a good enough solution for this :( I think we should keep it as HTML in that case. I'll make the change.

**Comment by oguzkocer** [comment]
@nbradbury I made that change in 91b93ae3421223e24691210890e7f56180f4e5e9. Ready for a second round!

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
