### PR TITLE
Refactor example app

### PR DESCRIPTION
**Pull request by maxme**
Split the MainActivity into fragments. Makes each "store" tests more readable.

### CODE REVIEW

**Comment by maxme** [comment]
Note: When this is merged, open a PR with the comments fragment: https://github.com/wordpress-mobile/WordPress-FluxC-Android/tree/issue/example-app-comments

**Comment by aforcier** [comment]
Crashes on rotation. 1 out of 5 stars.

**Comment by maxme** [comment]
> Crashes on rotation. 1 out of 5 stars.

Fixed in  	5e32c73

**Comment by aforcier** [comment]
Looks great! Love the restyled+scrollable log.

⭐️⭐️⭐️⭐️⭐️

:shipit:

**Pull request merged**
