### PR TITLE
Woo: Add a missing Coupon property

### PR DESCRIPTION
**Pull request by 0nko**
This PR adds a missing Coupon `amount` field to the DTO and and entity.

**To test:**
1. Run the DB migration and make sure it passes.
2. Run the example and verify there is a new `amount` column in the DB, using the App inspection tool

### CODE REVIEW

**Review by hafizrahman — APPROVED** [review]
This LGTM, thanks for working on it!

**Comment by hafizrahman** [comment]
Unit test is failing so I can't merge it, but it seems like an unrelated issue. CircleCi doesn't allow me to re-run it yet, though 🤔 

Screen Shot 2022-03-24 at 16 02 21

**Comment by 0nko** [comment]
> CircleCi doesn't allow me to re-run it yet, though 

Interesting. I thought it was just me. 

@ParaskP7 Do you know what could be causing this?

**Comment by ParaskP7** [comment]
👋 @0nko !

Thanks for the ping! 👍 

> @ParaskP7 Do you know what could be causing this?

Pinging @jkmassel as well since he might be the best to answer this. 🤔

**Pull request merged**
