### PR TITLE
UPDATE_SITE_PLUGIN_VERSION action renamed as UPDATE_SITE_PLUGIN

### PR DESCRIPTION
**Pull request by oguzkocer**
This is a continuation of #636 which needs to be merged in before reviewing this one. Please refer to the original PR #636 for more details.

/cc @aforcier

### CODE REVIEW

**Comment by oguzkocer** [comment]
I've rebased this PR due to [this fix](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/636#issuecomment-349124373)

**Comment by aforcier** [comment]
@oguzkocer looks like the rebasing went wrong in this branch.

**Comment by oguzkocer** [comment]
@aforcier It should be fixed now.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
