### PR TITLE
Woo/2353 order payment url

### LINKED ISSUE #2353: Woo: Add payment_url to order model
For simple payments, we'd like to enable sharing the payment link. This requires adding `payment_url` to the order model. Note that this field is only available in core v6.4+

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #2353 by adding `paymentUrl` to the order entity. Note that in order to test this you'll need to use a v6.4 store, which requires using the WooCommerce Beta Tester to update to the latest RC.

### CODE REVIEW

**Comment by wzieba** [comment]
@nbradbury as we merged #2287, now we have Room `2.4.2` with AutoMigrations. WDYT about trying that in this PR? I'm okay with the migration you provided as it is, just wondering if this is a good opportunity to try a new feature.

**Comment by nbradbury** [comment]
@wzieba Good call. I've added auto migration to this PR.

**Comment by wzieba** [comment]
Thanks! The code looks good, I'm starting to test it with WooCommerce instance, just to be very sure 🙂.

In the meantime, WDYT about adding test for this migration? I've experimented with it as using AutoMigrations requires some minor changes.

<details>
<summary> PATCH </summary>
<p>

```PATCH
Index: plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt b/plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt
--- a/plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt	(revision 3bae48e6c711543606f6f0dd28668c894d1ec004)
+++ b/plugins/woocommerce/src/androidTest/java/org/wordpress/android/fluxc/persistence/MigrationTests.kt	(date 1649785743321)
@@ -1,7 +1,7 @@
 package org.wordpress.android.fluxc.persistence
 
+import androidx.room.migration.AutoMigrationSpec
 import androidx.room.testing.MigrationTestHelper
-import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import androidx.test.platform.app.InstrumentationRegistry
 import org.junit.Rule
@@ -22,9 +22,9 @@
     @Rule
     @JvmField
     val helper: MigrationTestHelper = MigrationTestHelper(
-            InstrumentationRegistry.getInstrumentation(),
-            WCAndroidDatabase::class.java.canonicalName,
-            FrameworkSQLiteOpenHelperFactory()
+        InstrumentationRegistry.getInstrumentation(),
+        WCAndroidDatabase::class.java,
+        listOf<AutoMigrationSpec>()
     )
 
     @Test
@@ -114,6 +114,14 @@
         }
     }
 
+    @Test
+    fun testMigrate12to13() {
+        helper.apply {
+            createDatabase(TEST_DB, 12).close()
+            runMigrationsAndValidate(TEST_DB, 13, true)
+        }
+    }
+
     companion object {
         private const val TEST_DB = "migration-test"
     }


```

</p>
</details>

**Review by wzieba — APPROVED** [review]
Works as it should! Just leaving this one comment about test.

**Comment by nbradbury** [comment]
@wzieba Thanks for the assist on the migration test! Added in [6db22cc](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2354/commits/6db22cc20724328a9416923439cd7f33a49a63e0).

**Comment by wzieba** [comment]
Thanks! :shipit:

**Pull request merged**
