### PR TITLE
[Backend Receipts] Add the new endpoint

### LINKED ISSUE #10611: [Backend Receipts] Add the new endpoint to fluxc
```
POST /orders/<order id>/receipt
 
Query Params:
expiration_date: Formatted as yyyy-mm-dd.
expiration_days: A number, 0 is today, 1 is tomorrow, etc.
force_new: Defaults to false, if true, creates a new receipt even if one already exists for the order.
```

```
{
  "receipt_url": "https:\/\/very-child-traveler.jurassic.ninja\/wc\/file\/transient\/7e811783b66f468b61b4738231287b2a706ce1",
  "expiration_date": "2024-01-23"
}
```

### PR DESCRIPTION
**Pull request by kidinov**
The PR adds the endpoint:

https://github.com/woocommerce/woocommerce-android/issues/10611

```
POST /orders/<order id>/receipt
 
Query Params:
expiration_date: Formatted as yyyy-mm-dd.
expiration_days: A number, 0 is today, 1 is tomorrow, etc.
force_new: Defaults to false, if true, creates a new receipt even if one already exists for the order.
```

```
{
  "receipt_url": "https:\/\/very-child-traveler.jurassic.ninja\/wc\/file\/transient\/7e811783b66f468b61b4738231287b2a706ce1",
  "expiration_date": "2024-01-23"
}
```

There is e2e test yet, as the change is not deployed as release version of WC

### CODE REVIEW

**Review by backwardstruck — COMMENTED** [review]
I understand that there is no end to end test because the backend change has not yet been deployed. Is there anything else I can check?

**Comment by kidinov** [comment]
@backwardstruck, not really, but we can wait to merge it, as today I will have a PR that uses this call from the Woo app, so this can be checked in integration. I'll share the credentials with you of the site where the dev version of WC plugin installed

**Comment by backwardstruck** [comment]
> @backwardstruck, not really, but we can wait to merge it, as today I will have a PR that uses this call from the Woo app, so this can be checked in integration. I'll share the credentials with you of the site where the dev version of WC plugin installed

Got it. Linking this PR you referenced:
https://github.com/woocommerce/woocommerce-android/pull/10637

**Review by backwardstruck — APPROVED** [review]
Code changes look good. Related PR is already merged.

**Pull request merged**
