### PR TITLE
Implement retrieve of Space Quota information and store in on the model.

### PR DESCRIPTION
**Pull request by SergioEstevao**
#737 

This PR implements the fetching and storing of site quota information.

### CODE REVIEW

**Comment by maxme** [comment]
Patch looks good, but  the style checker is sad :( - you can run it from AS or run in cli: `./gradlew checkstyle`

What do you think of adding a new test in `ReleaseStack_SiteTestWPCom`?
```java
    @Test
    public void testSiteQuotaAllowed() throws InterruptedException {
        authenticateAndFetchSites(BuildConfig.TEST_WPCOM_USERNAME_TEST1, BuildConfig.TEST_WPCOM_PASSWORD_TEST1);
        // Get the first site
        SiteModel firstSite = mSiteStore.getSites().get(0);
        // Default quota for a wpcom site is 3Gb
        assertEquals(firstSite.getSpaceAllowed(), 3L * 1024 * 1024 * 1024);
    }
```

**Comment by aforcier** [comment]
Note that this will also need a [db migration](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/0226013fb4d73f67ff1d149d7f903d98c0085ef2/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.java#L80) to be added.

**Comment by SergioEstevao** [comment]
@maxme and @aforcier ready for another look

**Comment by oguzkocer** [comment]
@SergioEstevao We merged another PR today which also had a migration, do you mind merging `develop` into your PR and updating the migration? Thanks!

**Comment by maxme** [comment]
Looks good - :shipit: and congrats for your first FluxC PR!

**Pull request merged**
