### PR TITLE
Fix #293: new domain name idn tests

### LINKED ISSUE #293: Add tests for sites using IDNs

### PR DESCRIPTION
**Pull request by maxme**
Note: Emoji domain name test is failing due to an issue in WPUtils, I'll fix it and submit a PR there.

### CODE REVIEW

**Comment by maxme** [comment]
https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/10

**Comment by aforcier** [comment]
https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/10 has been merged.

**Comment by maxme** [comment]
> wordpress-mobile/WordPress-Utils-Android#10 has been merged.

I'll publish a new utils version and subtree pull it in wpandroid, the update this PR.

**Comment by maxme** [comment]
Updated to use wputils v1.14.1 - new tests pass.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
