### PR TITLE
Add lastModified to ListItemModel & PostModel

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR is a part of post pagination project. In order to figure out whether there is a change for a post in the DB, we need to get and store the `lastModified` date of the post in both `ListItemModel` and `PostModel`. When we fetch the details of a list, we'll now fetch both the `ID` and `lastModified` date of the post. This way, when the user pulls to refresh the list, we can identify which items' contents should be updated.

As part of this PR, I also renamed `PostListModel` to `ListItemModel` to make it more generic. I was intending to make this change at a later time, but I thought this would be a good PR to combine with and we'll have less things to refactor at a later time.

To Test:
* Check the `lastModified` date with breakpoints in the example app or from connected tests. Make sure to do a fresh installation since the migration is changed.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thank you @oguzkocer! 

The code looks good overall. I'm just wondering if [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/3ee3a0b25c153157fe32bf386f1f7c8a42e5c18c/example/src/test/java/org/wordpress/android/fluxc/utils/ListItemSqlUtilsTest.kt#L128) test and behavior of [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/3ee3a0b25c153157fe32bf386f1f7c8a42e5c18c/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/ListItemSqlUtils.kt#L18) method still makes sense. Wdyt? (We might consider modifying the `ListItemSqlUtilsTest` and make sure the new field is handled correctly.)

**Comment by oguzkocer** [comment]
Thanks for the review @malinajirka! The test definitely still makes sense, we don't want duplicate items in a list. However, the insert one is a great question and I am not 100% sure if I have the right answer for it.

The current behavior prevents from duplicate records ever occurring in the DB setup level, so it's guaranteed. It can prevent duplicate records in following 2 situations:
1. There are two records for the same item (post) in the fetched list from API. Assuming that the API is properly implemented, this should never happen and I don't think we should do anything special to handle it beside a general duplicate row prevention.
2. An item is fetched in (n)th page fetch from API and it's fetched again in (n+x)th page fetch again, where x > 0. This could happen if there is enough time between fetches and more records are added to a specific list in remote. However, this will very rarely happen, if ever.

As I said, I don't think we should even consider the first situation, but the changes in this PR affects how we handle the second situation. The way it works in this PR is, if we get a duplicate record in a different fetch, we just ignore it, which means we won't update the `lastModified` date. I think the probability of receiving a duplicate record that's `lastModified` date is different from the original record is very low, but it is still a fair situation to consider.

Handling this situation requires us to do an `insertOrUpdate` instead of just an `insert` which afaik means that it'll have to happen record by record as we can't implement this behavior as a batch. I am not sure if that tradeoff is worth handling such an edge case. I am still leaning towards not handling it, but even then we should at least have a comment there explaining the behavior. What do you think?

**Comment by oguzkocer** [comment]
Thanks a lot for the detailed follow up @malinajirka, your third point makes a lot of sense. I'll make the change.

> What I meant by this comment was, that it might be good to make sure in tests that retrieving and storing the new field works as expected. Wdyt?

I didn't realize the comment was added with the assumption that we'd change the current behavior. I'll see what we want to do with tests with this change whether to modify one or add a new one.

> This seems rare, but I think there are users for which it might not be so rare. Imagine you'd be following hundreds of sites.

This wouldn't have any affect on this issue, it's purely about edits. The number of sites that's being followed couldn't affect the getting duplicate posts in different pages as far as I know. Having said that, you already convinced me with your third point :)

**Comment by oguzkocer** [comment]
@malinajirka Sorry about the late follow up on this one. I wasn't sure if the `lastModified` property would stay in the `ListItemModel` and wanted to wait to decide on that before I made the changes to the tests. It turns out we don't need this property. We'll still need to fetch and save the `lastModified` date for Post (or some other field to see if the model has changed), but we don't need to keep track of it in the list data. That means we don't need to modify the tests either. The change has been made in `0827cb7780cb435beaef94d6e43203584fc8dc74` and the PR is ready for another look!

P.S: I wish I didn't make the changes to the `PostModel` in this PR. At the time, I needed these changes immediately, but since then the implementation has changed a lot and I'd have preferred to keep the Post specific changes in a separate PR. I could remove the changes, but since adding one property to a model is not a breaking change, I am just going to keep it since I'll need it eventually. @malinajirka if you have objections for that, I am happy to remove it until it's needed.

**Comment by malinajirka** [comment]
Thanks @oguzkocer! No worries at all :-).

> I could remove the changes, but since adding one property to a model is not a breaking change, I am just going to keep it since I'll need it eventually.

I agree.

>It turns out we don't need this property. We'll still need to fetch and save the lastModified date for Post (or some other field to see if the model has changed), but we don't need to keep track of it in the list data.

I'm not sure I understand this part. AFAIU we'll fetch list of post ids for a specific list id (let's say trashed posts) -> how do we decide which posts are out-of-date and we need to fetch them from the server?

**Comment by oguzkocer** [comment]
> I'm not sure I understand this part. AFAIU we'll fetch list of post ids for a specific list id (let's say trashed posts) -> how do we decide which posts are out-of-date and we need to fetch them from the server?

We'll still fetch the `lastModified`, but we just won't save it in the DB for `ListItemModel`. In your example, `PostStore` will be responsible for comparing the `lastModified` date in the fetched list with the current items in the DB to figure out which ones are out of date and dispatch an action to fetch them. So, we have pretty much the same logic, just in a different (correct) layer.

Furthermore, although `lastModified` is a pretty common property for many models in and out of WordPress ecosystem, afaik not all models have it. Sometimes, there might be a different field we can use to identify outdated models, such as `hash` and the store could decide which one to use.

This move just helps with the separation of concerns and saves us some query time. Hope this helps, let me know if you have any further questions!

**Comment by malinajirka** [comment]
I see, thanks for the clarification;)!

LGTM

**Pull request merged**
