### PR TITLE
[Nullability Annotations to Java Classes] Add Missing Nullability Annotations to `Media` Model Classes (`breaking`)

### LINKED ISSUE #2832: Nullability Annotations to Java Classes - SqlUtils & Model - Media
Parent #2799

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Media` sql-utils & model classes as possible, including fields, arguments, parameters, and return values.

- [MediaSqlUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/838d24279068169e761c5e356fd72392a4296198/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/MediaSqlUtils.java#L4)
- [MediaModel.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/838d24279068169e761c5e356fd72392a4296198/fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaModel.java#L4)

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2799
Closes #2832

This PR adds any missing nullability annotation to [MediaModel.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7fd7840a9bd900fde8e32ad8bd5632ad8f05dff3/fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaModel.java#L4) model and all related store & sql-util classes.

FYI: This change is `breaking`, meaning that any client that depended on the [MediaModel.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7fd7840a9bd900fde8e32ad8bd5632ad8f05dff3/fluxc/src/main/java/org/wordpress/android/fluxc/model/MediaModel.java#L4) model should update to the new APIs (`non-default constructors`) as the existing API (`default constructor`) are now deprecated. As such, this change is inherently `risky`, meaning that there are compile-time changes associated with this change and thus needs testing to verify correctness, both on the library's and client's side.

PS: Any other changes on any other class are just some propagating missing nullability annotation changes, which stem from the main set of classes being updated, this PR's focus, plus, some other extra minor analysis, refactor and test related changes.

-----

PS.1: @AjeshRPai I added you as the main reviewer, not so randomly (it being a continuation of #2878), since I just wanted someone from the Jetpack/WordPress mobile team to be aware of and sign-off on that change. Feel free to merge this PR directly yourself if you deem so.

PS.2: @0nko I am also adding you as an extra reviewer, not so randomly (it being a continuation of #2878), since I want someone from the WooCommerce mobile team to be aware of this change as well. However, there is no need for you to review it as well, thus duplicating the review work. Having one team member from either of the mobile teams reviewing and testing this change is enough for this change.

-----

Nullability Annotations List (`Model`):

1. [Add missing final keyword to field name on media fields enum](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/07c5b4a66c357f1575a81ee383dad1572b94ece0)
2. [Add missing nl-a to equals parameter on media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/71cd024084657b7b22875f6c85eb38376d82a450)
3. [Add missing nl-a to upload state field on media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/cd2554992b0ef2a78bb4491492a7cded2d078cc6)
4. [Add missing nn-a to fields to update field on media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/ed262b8e14efae280021c0c8902be662f034210f)
5. [Add missing n-a to media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/00393cd777dbce27478de8b73de325c97578a5ab)
6. [Add default and non-default constructors for media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/2c13cd47ffe713bdd21eeec868ea04c1ae085ada) (`breaking`)

Nullability Annotations List (`Store`):

1. [Add missing n-a to media error type enum on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/dea7a5337bcd0bd1faedb56f6a08994dbee09a00)
2. [Add missing n-a to media error on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/63d05c6137b822ad5767bfe34ecfb8108a9a2b83)
3. [Add missing n-a to upload stock me type enum on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/9e1a12e3b3f1339fadcd8f76d238fa8145093f2d)
4. [Add missing n-a to upload stock me on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/f1295c231039f9897131f4bbd666e15a248ac466)
5. [Add missing n-a to on media changed on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/991b061454c128a256ff3cc2f11a7cc091dbfcaa)
6. [Add missing n-a to on media list fetched on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/a32c193364f314877c2bb2d1ede0dbb687a4e213)
7. [Add missing n-a to on media uploaded on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/6232ab638ecd56f1c048793322028318356f0a52)
8. [Add missing n-a to get (all) site media (count) on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/f7a53ff9b1958d78064b9af8c736307b0ef60ded)
9. [Add missing n-a to has/get site media with id on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/9d81ae952546aaad51e8717d29735931d770d9b4)
10. [Add missing n-a to get media with local id on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/fae9905b25b7c04dfb9b9d0e9d5b1c12dad49b34)
11. [Add missing n-a to get site media with ids on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/b5991879c35cd29d84dcf29210a6590834c860ee)
12. [Add missing n-a to get images/videos/audio/docs on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/0b74851cee5a7abcf0fc7885cfbc4e66bda1712b)
13. [Add missing n-a to get site images excl. ids on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/07eb3b9d6f7f7479dfdd8b4284d0c411ab1a485a)
14. [Add missing n-a to match site media related on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/b2bc82313ff0c7b47157289b3bcddbba50f5a7f7)
15. [Add missing n-a to get local site media on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/2c4ae2b04a04adb8da174cf715b47af7abafb306)
16. [Add missing n-a to get thumbnail url for smi on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/9c2ec88d4af6a751138dd3d9c326f40ff5547d16)
17. [Add missing n-a to search site related on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/7a0f04279f93b4f4cbfbc6908403252fbfd6cd60)
18. [Add missing n-a to match post media related on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/3627104206fd934ff1dad3a38238378b7bb37a06)
19. [Add missing n-a to remove media on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/b0e273d7e0c326598c7b2c44f585ff481320a0e1)
20. [Add missing n-a to perform upload stock media on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/a3168f28ece91993497b2f9486aae5077334d870)
21. [Add missing n-a to handle stock media uploaded on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/dcac956f473d0d7254b957255605652cb86905e0)

Nullability Annotations List (`SqlUtils`):

1. [Add missing n-a to get media with sq on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/4edf1c93d2e8c7dd884616c21890119a98e8dcf6)
2. [Add missing n-a to get with states related on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/c476f0ee1251c871fc5e29f79ce0685137781adc)
3. [Add missing n-a to get insert media related on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/90215b94213e282df4435ef7da49118479243d39)
4. [Add missing n-a to get delete media related on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/ea0f8f1f3dd6d33e4ac5f1d3d46e7be0552aba51)

Nullability Annotations List (`Utils`):

1. [Add missing n-a to is (supported) related on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/639fbf398496c9a2999a2b14ca46297399b53052)
2. [Add missing n-a to get mime type for extension on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/1579f612112879be5e3205ceeac20f84f1767ece)
3. [Add missing n-a to can read file on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/e425e8d4b86b31d8223c37ea61ff40b81e9e3516)
4. [Add missing n-a to get extension on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/1aa94c82ce06142c9d8729a752c78e5ad03d5180)
5. [Add missing n-a to get file name on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/beb0a2624845409e035bfacd03f912e4827076b6)
6. [Add missing n-a to strip location on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/d0c01974ed8a93421228505521ae2f3c1278b2f5)

Warnings Resolution List:

1. [Make strip location method void on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/8cefe9d31ca641481236fed29c6bd8992ef78cb2)
2. [Make delete related methods void on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/d88035220b6419a045e63f22a8f8731cf11e542c)

Warnings Suppression List:

1. [Suppress condition covered by further condition warning](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/9b0c22b71643232212001bfa2d427e334cf31b0c)
2. [Suppress unused warning on media model](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/f7809a32009b3eb82579bacf7a7c8fde7018d2e0)
3. [Suppress unused warning on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/3add2d49b2aba082fd11bac21c2f6165b6deae29)
4. [Suppress boolean method is always inverted warn on media utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/b10ff95844694fab99688c41d3f836f7dc656f2e)
5. [Suppress unused warning on media sql utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/db4c0f6a9648e12a3f50ebdb5880afbbf9c5b427)

Refactor List:

1. [Move static not deleted states field to top on media store](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/297ba53bc19b28f22e570a66d6f569f2cc4eb619)

Test List:

1. [Use property access syntax on media error test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/dc8d65c552db8007a3383e3674790b08b6123b99)
2. [Simplify assert true assertion on media test utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/cc7928c52a902341da1346f9a75c6c17dbca5518)
3. [Reformat mocked stack media test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/d54040e68b41b8c6e829fa0246cc2cf4f45126b2)
4. [Add missing final to media store on media utils test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/b8b71f9a47cf7cbff502aed3bddfce7a5fbb6645)
5. [Add missing final to media store on media sql utils test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/999c1a9c0316d8c2d33f82bd66e7af5bb22bec93)
6. [Suppress constant value warning on media sql utils test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/1759268b2a22e237e582572dbbc8e892b40fa57e)
7. [Delete unneeded test match post media test on media sql utils test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/ec188d7042e059d385397cf5bfe6568a2b82c765)
8. [Remove interrupted exception from throws list on media su test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/7ec75fb0c3c14448288f28f98dda513f63c9c68d)
9. [Simplify insert helper functions on on media sql utils test](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2886/commits/e47338a4c9cc68b15d2a0618e4ef4d9e120bd34d)

-----

## Associated Clients

It is highly recommending that this change is being tested on the below associated clients:

- [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android)
- [WCAndroid](https://github.com/woocommerce/woocommerce-android)

-----

## To Test (`REST`):

- Smoke test the `FluxC Example` app via the `MEDIA` screen. Verify everything is working as expected.
- In addition to the above, using [local-builds.gradle](https://github.com/wordpress-mobile/WordPress-Android/blob/44a6d0611175f132ff6920b4d6a3e16d565259b6/local-builds.gradle-example#L18) on [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android), smoke test any media related functionality on both, the WordPress and Jetpack apps, and see if everything is working as expected. For a couple of examples, you can expand and follow the inner and more explicit test steps within:
- Furthermore, using [local-builds.gradle](https://github.com/woocommerce/woocommerce-android/blob/trunk/local-builds.gradle-example) on [WCAndroid](https://github.com/woocommerce/woocommerce-android), smoke test any media related functionality and see if everything is working as expected. For a couple of examples, you can expand and follow the inner and more explicit test steps within:

## To Test (`XMLRPC`):

- Create a new self-hosted WordPress site for XMLRPC testing purposes ([jurassic.ninja](https://jurassic.ninja/)).
- Smoke test the `FluxC Example` app via the `MEDIA` screen. Verify everything is working as expected.
- In addition to the above, using [local-builds.gradle](https://github.com/wordpress-mobile/WordPress-Android/blob/44a6d0611175f132ff6920b4d6a3e16d565259b6/local-builds.gradle-example#L18) on [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android), smoke test any media related functionality on both, the WordPress and Jetpack apps, and see if everything is working as expected. For a couple of examples, you can expand and follow the inner and more explicit test steps within:
- Furthermore, using [local-builds.gradle](https://github.com/woocommerce/woocommerce-android/blob/trunk/local-builds.gradle-example) on [WCAndroid](https://github.com/woocommerce/woocommerce-android), smoke test any media related functionality and see if everything is working as expected. For a couple of examples, you can expand and follow the inner and more explicit test steps within:

<details>
    <summary>[JP/WP] Media Screens [MediaBrowserActivity.java + MediaGridFragment.kt + MediaSettingsActivity.java + MediaPreviewActivity.java + MediaPreviewFragment.java]</summary>

ℹ️ This test applies to both, the `Jetpack` and `WordPress` app.

- Go to `Media` screen, verify it is shown and functioning as expected.
- For example try changing tabs, searching and adding a new media.
- Tap on any media and verify that the `Media Settings` screen is shown and functioning as expected.
- For example try updating the media title or adding a media description.
- Tap on the media preview and verify that the `Media Preview` screen is shown and functioning as expected.
- For example try swipe left-right to navigate between media previews.

</details>

<details>
    <summary>[WC] Photos Screens [ProductDetailFragment.java + ProductImagesFragment.kt + ProductImageViewerFragment.kt]</summary>

- Go to `Products` tab and tap on any product.
- Tap on any photo on top and verify that the `Photos` screen is shown and functioning as expected.
- For example try adding a new photo, select an upload method, and wait for the photo to be uploaded.
- Tap on the photo preview and verify that the `Photo Preview` screen is shown and functioning as expected.
- For example try swipe left-right to navigate between photo previews.

</details>

-----

## Merge instructions:

1. [x] Wait for the accompanying [JP/WPAndroid#19506](https://github.com/wordpress-mobile/WordPress-Android/pull/19506) to be reviewed and approved.
2. [x] Wait for the accompanying [WCAndroid#10078](https://github.com/woocommerce/woocommerce-android/pull/10078) to be reviewed and approved.
3. [x] Remove the `[PR] Not Ready for Merge` label.
4. [x] Merge this PR.
5. [x] Follow-up with the merge instructions on the accompanying [JP/WPAndroid#19506](https://github.com/wordpress-mobile/WordPress-Android/pull/19506) client PR.
6. [x] Follow-up with the merge instructions on the accompanying [WCAndroid#10078](https://github.com/woocommerce/woocommerce-android/pull/10078) client PR.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: Per the merge instructions within the PR description, I am going to create the accompanying [JP/WPAndroid#TODO](TODO) and [WCAndroid#TODO](TODO) PRs tomorrow. Until then, feel free to start the review process and test this PR with the `FluxC Example` app, since, you won't be able to test this with [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android) or [WCAndroid](https://github.com/woocommerce/woocommerce-android) just yet. I'll let you know with another comment when each of those accompanying PRs get ready.

**Comment by ParaskP7** [comment]
FYI: The accompanying [JP/WPAndroid#19506](https://github.com/wordpress-mobile/WordPress-Android/pull/19506) PR is up and ready. As such, the code review on the [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android) side can be fully completed. @AjeshRPai

**Comment by ParaskP7** [comment]
FYI: The accompanying [WCAndroid#10078](https://github.com/woocommerce/woocommerce-android/pull/10078) PR is up and ready. As such, the code review on the [WCAndroid](https://github.com/woocommerce/woocommerce-android) side can be fully completed. @0nko

**Review by 0nko — APPROVED** [review]
I've tested the FluxC Example app and I found no issues 👍. 

As for the code changes, I've looked at the parts that are relevant to WCAndroid and it looks good. I'll let @AjeshRPai take a more detailed look since he's probably more familiar with it.

I already mentioned it in the WCAndroid PR, but we'll also want to update the MediaPicker library.

👏

**Comment by ParaskP7** [comment]
Thank you so much for reviewing, testing and approving these and the changes in the accompanying [WCAndroid PR](https://github.com/woocommerce/woocommerce-android/pull/10078) @0nko , you are awesome! 🙇 ❤️ 🚀 

> I already mentioned it in the WCAndroid PR, but we'll also want to update the MediaPicker library.

Oh true, this is interesting, I'll response to that in the accompanying [WCAndroid PR](https://github.com/woocommerce/woocommerce-android/pull/10078), thanks for mentioning [MediaPicker](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android), I knew I picked the right person for this review! 💯 😊 💯

**Review by AjeshRPai — APPROVED** [review]
I have tested the changes in this PR using the accompanying https://github.com/wordpress-mobile/WordPress-Android/pull/19506 and everything looks good to me 👍🏼 

I am approving but not merging since this change also affects WCAndroid.

**Comment by ParaskP7** [comment]
Awesome, thank for reviewing and testing this @AjeshRPai , you rock! 🙇 ❤️ 🚀 

FYI: I'll proceed with the merging myself. 🙏

**Pull request merged**
