### PR TITLE
Media client lint fixes

### PR DESCRIPTION
**Pull request by aforcier**
Just cleaning up a few linter issues in the media clients - mostly using specific imports, and making a few `null` usages explicit.

### CODE REVIEW

**Comment by maxme** [comment]
I wonder if we can enable a rule in checkstyle for this.

**Comment by aforcier** [comment]
> I wonder if we can enable a rule in checkstyle for this.
If not, we could make Travis treat all lint warnings as errors :trollface:

**Comment by aforcier** [comment]
> I wonder if we can enable a rule in checkstyle for this.

Following up on this - as we discussed there isn't a rule for this, and there's also no straightforward way of getting Travis to run Android Studio's inspections. Abandoning standardizing this particular inspection.

So, uh, ready for review @maxme 😉

**Comment by maxme** [comment]
:shipit:

**Pull request merged**
