### PR TITLE
Improve Attributes JSON data error handling

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix for the `ReleaseStack_WCProductTest#testUpdateDownloadableFiles` test. After the Attributes parameter addition when updating a Product or Product Variation, no treatment was added for scenarios where the new Attributes JSON value is null, this fix introduces simple handling to set an empty JSON array instead of trying to parse a null value as JSON.

How to Test
==========
Just make sure the test `ReleaseStack_WCProductTest#testUpdateDownloadableFiles` no longer fails at the `Connected Tests` CircleCI Job.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey, @aforcier @0nko , I've created this PR to fix the failing test we talked about before, would you mind taking a look if this solves this issue on your side too? Thanks!

**Review by 0nko — COMMENTED** [review]
The JSON error is fixed, but I'm still seeing failing tests:

image

```
2021-02-24 09:57:51.280 5074-10803/org.wordpress.android.fluxc.example E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-17
    Process: org.wordpress.android.fluxc.example, PID: 5074
    org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
        at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
        at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:430)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
        at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41)
        at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32)
        at org.wordpress.android.fluxc.store.CommentStore.handleFetchCommentsResponse(CommentStore.java:429)
        at org.wordpress.android.fluxc.store.CommentStore.onAction(CommentStore.java:227)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.AssertionError: Error occurred for event: COMMENT_CHANGED with type: GENERIC_ERROR
        at org.wordpress.android.fluxc.release.ReleaseStack_CommentTestXMLRPC.onCommentChanged(ReleaseStack_CommentTestXMLRPC.java:310)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:430) 
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411) 
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384) 
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:265) 
        at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41) 
        at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32) 
        at org.wordpress.android.fluxc.store.CommentStore.handleFetchCommentsResponse(CommentStore.java:429) 
        at org.wordpress.android.fluxc.store.CommentStore.onAction(CommentStore.java:227) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507) 
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by ThomazFB** [comment]
Hey @0nko, thanks for your review! Correct me if I'm wrong, but I thought that the newly introduced test error was the `ReleaseStack_WCProductTest#testUpdateDownloadableFiles` which was flagged by @aforcier. I decided to take a look at these other three failing tests and I'm not confident about what can possibly be going on since they're more related to the WP Android calls, but from my investigations, it looks like these other three were already happening. Do we know someone that can possibly have a better guess about these Comments failing tests that we can ask for help?

**Comment by aforcier** [comment]
Confirming that `ReleaseStack_WCProductTest#testUpdateDownloadableFiles` passes for me with this PR 👍  Thanks @ThomazFB 

About the failing comment tests - those are passing locally for me, I'm not sure if there was a hiccup with the site or some config issue on your end (seems unlikely if you're both having the tests fail 🤔).

In any case, let's merge this to fix the obvious/consistent broken one and keep an eye on the comment ones for further failures.

**Comment by 0nko** [comment]
@ThomazFB Oh yeah, you're right. 

@aforcier Sounds good 👍

**Pull request merged**
