### PR TITLE
Clear Account & Token on Invalid Token

### LINKED ISSUE #462: Clean token and account on INVALID_TOKEN error
We receive an `invalid_token` error from WP.com if the token used by the app has been invalidated. In this case we should flush the token and account data - otherwise it becomes impossible to sign back into WordPress.com.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #462 
## Findings
When the token is invalid, the account and access token isn't being cleared in the `AccountStore` but there was a `signOut` function that contained some of the logic to do so. 

## Solution
To replicate the signout behavior when the `invalid_token` event is published so once the client consumes it's known that all account data has been invalidated. 

## Testing
1. Use this [WP Android branch with the FluxC hash
](https://github.com/wordpress-mobile/WordPress-Android/pull/11048)
2. Sign in to the app and select a WP.com site. 
3. Go to  https://wordpress.com/me/security/connected-applications on the same profile signed in above and disconnect WordPress Android. 
4. Try to utilize functionality such as Account Settings and the app should log out. 
5. Log back in and the app won't redirect you to the login when it's successful. 

N.B 
1. When I use my Automattic email this error doesn't occur. I haven't finished investigating that as yet.
2. I didn't do any tests with a self-hosted site. 

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by jd-alexander** [comment]
Hi @oguzkocer 
Thanks for the review and feedback. 

> If the only thing we want to do is to remove the authentication token when we get INVALID_TOKEN error, this PR looks good. 👍 However, I wonder if it's better to completely sign the user out and clear their data in which case just the following should be enough:
` 
if (payload.error.type == AuthenticationErrorType.INVALID_TOKEN) {
    signout();
} `

Yes, this does work. I didn't do this because it seems the logic within the app wants to know when the token is invalid so that it can carry it out a specific flow for both WP.com and self hosted sites as seen [here](https://github.com/wordpress-mobile/WordPress-Android/blob/61bdde14a33672da02890b9b784efe8f719a8655/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L1032). So that's the reason I opted to simply clear the token and account and keep the existing logic. Nonetheless, I am going to have another look to be sure of this.

> What do you think @jd-alexander? Is there anyone (a designer, a lead, DRI etc) we can consult on this if there is no specific decision made yet? If there is a decision made to do it like this, I am happy to merge this PR as is. Just making sure that we understand how this will work.

Based on my understanding of the problem, correct me if I am wrong 😄 the solution I created will keep the current design and flow that is already working fine and simply resolve the sign-in bug where the app isn't signing in correctly because they weren't cleared. Let me know what you think 😄

**Comment by oguzkocer** [comment]
> Based on my understanding of the problem, correct me if I am wrong 😄 the solution I created will keep the current design and flow that is already working fine and simply resolve the sign-in bug where the app isn't signing in correctly because they weren't cleared. Let me know what you think 😄

Yeap, it definitely does and if that's exactly what we want, please feel free to 🚢 this as is. I just wanted to make sure that that's the case and we are making a conscious decision here and not missing the side effect of it.

**Comment by jd-alexander** [comment]
> Yeap, it definitely does and if that's exactly what we want, please feel free to 🚢 this as is. I just wanted to make sure that that's the case and we are making a conscious decision here and not missing the side effect of it.

Thanks for this. I am going to run a final test and share the results before merging this just to make sure!

**Comment by jd-alexander** [comment]
Hi @oguzkocer, 
here are two videos with the before and after of the login experience that were created with the associated WP Android. 

Before | After 
--------|-------
[Before Video ](https://drive.google.com/file/d/1AV2U7lcMHlSYNACgIq1J61cQfYsZYRQD/view?usp=sharing) |   [After Video   ](https://drive.google.com/file/d/1AZfLQXTDCRH5iF4arrEE2LZbr-ifvbZm/view?usp=sharing)

The only thing I discovered was a separate bug with self-hosted sites on `develop` where it continuously jumps to different screens when the token has been invalidated. 

Video | 
--------|
[Self Hosted Issue ](https://drive.google.com/file/d/1ARo-TCGlHWbvWF-dxaYBbhD3EhNtwt-C/view?usp=sharing) |   

This issue is separate from the one being addressed here so this PR could be merged and then a new issue is created. Let me know what you think about the videos and if there are any other cases that need to be tested. I just tested the sign-in/sign out experience that triggers the path the modifications were made to.  :)

**Comment by oguzkocer** [comment]
Thank you for the videos @jd-alexander! I was able to replicate the same behavior in my tests when I reviewed the PR, but I think it's good that it's documented here.

:shipit:

**Pull request merged**
