### PR TITLE
Introduced Fetch Supported States API

### PR DESCRIPTION
**Pull request by usamahamid**
This is an API required for implementing [custom domain association](https://github.com/wordpress-mobile/WordPress-Android/issues/7923) feature.

When User associates a custom domain, they have to input and confirm basic information about themselves.
In this screen, they will be required to select one of the supported states for a countries.

This API provides a list of supported states for a specific country from which User can select.

### CODE REVIEW

**Comment by usamahamid** [comment]
@malinajirka , This PR introduces a new API to fetch supported states for a specific country to be listed in the domain registration page.
Please do check it out, when you have a free moment

**Comment by malinajirka** [comment]
Thank you @usamahamid. It looks good overall, can you please resolve the conflicts. Thanks!

**Comment by usamahamid** [comment]
@malinajirka, Thanks for the review.
I have fixed the merge conflict and the PR is ready for another pass.

**Comment by malinajirka** [comment]
Thanks! LGTM

**Pull request merged**
