### PR TITLE
Move All time insights to live data

### PR DESCRIPTION
**Pull request by planarvoid**
This is adding Live data as an additional endpoint to the `StatsSqlUtils`. The solutions should scale well and we could use it for all the other endpoints. Let me know what you think @0nko 

I'm not sure at the moment how to update the LiveData value (it should be done on the main thread).

### CODE REVIEW

**Comment by planarvoid** [comment]
@oguzkocer thanks for commenting!

> I always felt that `LiveData` was a UI thing 

I felt exactly the same thing honestly. I think the problem is the way Google uses `LiveData`. After the DroidCon London talks I was somehow convinced it is ok to bubble LiveData down. I was considering other reactive options. I'd personally prefer using a coroutine broadcast channel but that's still experimental even for coroutines and I don't want to rewrite everything with every library change. Using RxJava is a huge overkill. LiveData is a very simple object which (I feel) could be easily replaced by something else in future. 

> I'd still prefer not to do it myself
> moving the LiveData creation to the Store layer

My thinking here was that we could easily replace our DB with Room once we decide to and the interface of the `SqlUtils` class wouldn't change. I could use Room here directly but it felt like a bigger change. I'm still not convinced this is the cleanest solution. I might still rewrite this in coroutine channels.

> You can use postValue from any thread

Generally you're right. Whenever working with coroutines in the UI layer I try to use `setValue` as much as possible since it's synchronous and that makes it much easier to test. If you do `withContext(Main) { liveData.value = "value" }` instead of `liveData.postValue("value")`, you can make it synchronous in tests. It also behaves predictably in a coroutine and you avoid some possible races.  

Also this PR is kind of exploratory. I don't think this solution is production ready. I'm totally open to comments.

**Comment by 0nko** [comment]
> I always felt that LiveData was a UI thing and shouldn't live in the lower layer

Just to add to @planarvoid's comment, I also don't think this is true - no more than using RxJava's Observables in lower layers is wrong. You don't need to observe on LiveData from, say, data layer directly. You can let the value propagate up to ViewModel's LiveData using [Transformations](https://developer.android.com/reference/android/arch/lifecycle/Transformations). That's why Google uses it in Room and it's ok.

> You can use postValue from any thread.

I tried to strictly follow this approach in PPP but after experiencing some weird behaviour (race conditions) I realized that you can't rely on `LiveData.value` property anymore because it's updated asynchronously. I needed to use it because the same ViewModel instance was used in different fragments and I needed to check the current state of data-loading.

**Comment by oguzkocer** [comment]
> My thinking here was that we could easily replace our DB with Room once we decide to and the interface of the SqlUtils class wouldn't change. I could use Room here directly but it felt like a bigger change. I'm still not convinced this is the cleanest solution. I might still rewrite this in coroutine channels.

@planarvoid That makes sense to me. I am glad that you're exploring this because there are some tidbits about LiveData I am still trying to wrap my head around and I'd love to hear your thoughts when you make a decision one way or another.

> Just to add to @planarvoid's comment, I also don't think this is true - no more than using RxJava's Observables in lower layers is wrong. You don't need to observe on LiveData from, say, data layer directly. You can let the value propagate up to ViewModel's LiveData using Transformations. That's why Google uses it in Room and it's ok.

@0nko Agreed 100%. I tried to explain the same thing in my comment, sorry if it wasn't clear. I was just sharing how it made me feel when I first worked on it, but I don't see anything inherently wrong with using `LiveData`, but there are things to consider, so on to my next response ->

> I tried to strictly follow this approach in PPP but after experiencing some weird behaviour (race conditions) I realized that you can't rely on LiveData.value property anymore because it's updated asynchronously. I needed to use it because the same ViewModel instance was used in different fragments and I needed to check the current state of data-loading.

That was actually my first realizations about `LiveData` that made me question how to best build around it. As I understand it, and this might be completely wrong, it's meant to be consumed by either consuming in the UI or by propagating/transforming to a different LiveData instance.

The threading issues are actually not specific to `LiveData` and `postValue`, modifying a state from a bg thread (such as FluxC event) and then reading it from another one. Using `setValue` kind of bypasses this issue by being able to sequence actions, but that mostly works on the UI side and harder to do in FluxC.

My take on this issue is to avoid it completely if it's at all possible, and in most cases with the right design, it is. That right design doesn't come naturally to me yet and I am still trying to figure this out myself, but just trying to say that, that's where I am putting my most effort in. It's hard to explain this without a concrete example, so I'll spare the details, but if you experience these race conditions due to threading (`postValue` or not) I'd love to take a look and talk about it.

Thank you both for following up on my comments, really appreciate it :)

**Comment by planarvoid** [comment]
@oguzkocer My take on the threading is that you always have to update the value from a BG thread and use it on the main thread. RxJava has this built in with the `subscribeOn` / `observeOn` approach. The dispatcher does this for us on the layer between FluxC and the app. The `LiveData` approach is the `postValue` which does basically the same. Asynchronously updates the value and propagates it on the main thread. The issues we were facing were caused by having multiple LiveData instances and by using `postValue` on all of them. In that case we can't be sure which one gets updated first. I think that's an expected behaviour. 

If we decided to use coroutine channels, I think it would make our lives easier because we would push the jump on the main thread to the View layer which is where it should happen anyway. The only downside is that it's still experimental. On the other hand it's a solution that's platform independent and will probably be around for a while. I might try to rewrite this PR with the channels to see how it works.

**Comment by oguzkocer** [comment]
> My take on the threading is that you always have to update the value from a BG thread and use it on the main thread.

Right, that's a part of avoiding the threading issues completely. That's why I force myself to use `postValue` all the time and not rely on the `value` of the `LiveData` except for in UI. In other cases, if we do need to act on it, it's probably better to transform it in some way to another `LiveData` that the UI will eventually use. (These are so hard to explain properly without a concrete example)

> The issues we were facing were caused by having multiple LiveData instances and by using postValue on all of them. In that case we can't be sure which one gets updated first. I think that's an expected behaviour.

Yeah, that's why I think everything has to be designed in way that sequencing actions doesn't matter. That's what I was trying to say before, but it's easier said than done in some cases. When that's not possible, or convenient, I think `MediatorLiveData` might help, but it's hard to say.

> I might try to rewrite this PR with the channels to see how it works

Sounds good. I haven't actually had the time to check the specifics of this PR, but when I find the time for it, I'll try to check out both of them.

**Pull request closed without merging**
