### PR TITLE
Updates to MediaStore to correctly identify and report malformed media errors on push actions

### PR DESCRIPTION
**Pull request by tonyr59h**
See #214 for details.

cc @oguzkocer

### CODE REVIEW

**Comment by oguzkocer** [comment]
Sorry @tonyr59h, I missed this PR. I'll review it as soon as I can.

**Comment by tonyr59h** [comment]
No problem 😄  Ready as of 8924a1d1d2db826f900a9b493e86a060403ffad8

**Comment by oguzkocer** [comment]
@tonyr59h it looks like this PR is breaking `testDeleteNullMedia` & `testDeleteMediaThatExists`.

**Comment by tonyr59h** [comment]
Okay, all fixed up now @oguzkocer. I tested on an API 16 emulator and API 23 device with fresh installs of the app that was just cleaned and re-built...no failing tests after 3 runs on each device.

**Comment by aforcier** [comment]
I mentioned this elsewhere but I'm adding a note here for visibility - the merge in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/233/commits/7449ded17309dc4a84c541a88d942a4f8555dd8d went badly and reverted some of the changes made in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/231.

**Comment by tonyr59h** [comment]
> I mentioned this elsewhere but I'm adding a note here for visibility - the merge in 7449ded went badly and reverted some of the changes made in #231.

I opted to use my version of the media test classes for that merge since I had just finished re-working them. 0ca3c3c39b1e666770363eb26e91ed039ad63328 adds all the changes you made back to them.

**Comment by aforcier** [comment]
> I opted to use my version of the media test classes for that merge since I had just finished re-working them. 0ca3c3c adds all the changes you made back to them.

👍 looks good

One small nit - should be able to eliminate `site` entirely [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/233/commits/0ca3c3c39b1e666770363eb26e91ed039ad63328#diff-d1032009dc29eb8d9f7b6de3425c3172R52) and just rely on `sSite` (there are a few more cases in that file).

**Comment by oguzkocer** [comment]
The tests are working for me as well. @tonyr59h if you can fix the issue @aforcier mentioned, I am ready to merge this in.

**Comment by tonyr59h** [comment]
Fixed in a57bc575b6191fbf2db0a9a6ee9ccfd32a50c3c5

**Comment by oguzkocer** [comment]
Looks good :shipit:

**Pull request merged**
