### PR TITLE
Add asc+desc parameters to some getters

### PR DESCRIPTION
**Pull request by maxme**
Note: I wanted to add the same parameter to all getters returning a `List<PostModel>` in the `PostStore`, but I noticed local drafts always come first and I want to avoid having a `orderByAscendingPublishingDateExceptForLocalDraftThatComesFirst` parameter ;)

### CODE REVIEW

**Comment by aforcier** [comment]
The instrumentation tests need to be updated to use the new param for `getCommentsForSite()` calls - they're currently broken.

**Comment by aforcier** [comment]
> Note: I wanted to add the same parameter to all getters returning a List<PostModel> in the PostStore, but I noticed local drafts always come first and I want to avoid having a orderByAscendingPublishingDateExceptForLocalDraftThatComesFirst parameter ;)

Yes that's a good point, I think it makes sense not to generalize this for now.

**Comment by maxme** [comment]
> The instrumentation tests need to be updated to use the new param for getCommentsForSite() calls - they're currently broken.

Fixed in  e110be8

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
