### PR TITLE
[Build] Upgrade Gradle to 8.2.1 and AGP to 8.1.0

### PR DESCRIPTION
**Pull request by ParaskP7**
Platform Request: `pdnsEh-13V-p2`
Project Thread: `paaHJt-57Z-p2`

This PR upgraded Gradle to [8.2.1](https://docs.gradle.org/8.2.1/release-notes.html) and AGP to [8.0.2](https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2).

FYI: The [8.1.1](https://docs.gradle.org/8.1.1/release-notes.html) Gradle upgrades had to happen in 2 parts (e98cb406513423f4e41f28ee8b409fc47ace055e and b431a77ea13bb063b8bf5f56b9db228c467494a0). This is because of the breaking changes that this upgrade introduces, including the `AGP` upgrade and its associated breaking changes (namespace, build option, etc).

-----

🚫 Blocked By:

- [ ] `Android Gradle plugin requires Java 17 to run. You are currently using Java 11.`

<details>
    <summary>CI Failure</summary>

```
[2023-07-11T14:37:28Z] FAILURE: Build failed with an exception.
--
  | [2023-07-11T14:37:28Z]
  | [2023-07-11T14:37:28Z] * Where:
  | [2023-07-11T14:37:28Z] Build file '/var/lib/buildkite-agent/builds/ci-android-i-0c1578ff840e2a51c-1/automattic/wordpress-fluxc-android/example/build.gradle' line: 1
  | [2023-07-11T14:37:28Z]
  | [2023-07-11T14:37:28Z] * What went wrong:
  | [2023-07-11T14:37:28Z] An exception occurred applying plugin request [id: 'com.android.application', version: '8.0.2']
  | [2023-07-11T14:37:28Z] > Failed to apply plugin 'com.android.internal.application'.
  | [2023-07-11T14:37:28Z]    > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
  | [2023-07-11T14:37:28Z]       Your current JDK is located in /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.x86_64
  | [2023-07-11T14:37:28Z]       You can try some of the following options:
  | [2023-07-11T14:37:28Z]        - changing the IDE settings.
  | [2023-07-11T14:37:28Z]        - changing the JAVA_HOME environment variable.
  | [2023-07-11T14:37:28Z]        - changing `org.gradle.java.home` in `gradle.properties`.
```

</details>

-----

Breaking Change List:

1. [Move package from android manifest to build files](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/83f52170bf43b239bb9bf65a49b9ed1237966daa)
2. [Enable build config build feature for fluxc and example](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/3720ba73d115e84b6ffa09a73c612def0d1a9314)
3. [Update kotlin to 1.6.20 (tmp)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/125faf48cbd0a0461b586e4ca0611a19976360af)
4. [Update rest assured to 5.3.1 (tmp)](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2772/commits/d852ece9be48dc5da9bf9b952c995fefdd3047ef)

AGP Upgrade Assistant List:

1. [Migrate dsl properties from lint options to lint](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/3bc6094374d168b687708d1d0dbdeab752115826)

-----

## Associated clients

You can reference the `[Build] Upgrade Gradle to 8.1.1 and AGP to 8.0.2` PRs of the below associated clients for testing/verification purposes:

- [ ] [WPAndroid##18775](https://github.com/wordpress-mobile/WordPress-Android/pull/18775)
- [ ] [WCAndroid#9427](https://github.com/woocommerce/woocommerce-android/pull/9427)

-----

## To test

1. Verify that all the CI checks are successful.
5. Test composite builds via the associated clients apps (see above).

-----

## Merge instructions

- [x] Mark PR as `Ready for review`.
- [x] Wait for PR to get approved (`tentatively`).
    - [x] TODO: Test all the PRs together once done with the reviews (@oguzkocer).
- [x] Remove [PR] Not Ready for Merge label.
- [x] Update `Catalog` with latest version and remove `androidGradlePlugin/kotlin/restAssured` version TODOs.
- [x] In coordination with all the other library and client PRs, merge this PR only when every PR is ready to be merged.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]
@ParaskP7 I am tentatively approving this PR pending testing. I'll test all the PRs together once I am done with the reviews. Hope that works for you!

**Comment by ParaskP7** [comment]
Awesome @oguzkocer , thanks for adding JDK17 support to this repo, then reviewing and tentatively approving the changes, pending some extra testing! 🙇 ❤️ 🚀 

FYI: I went ahead, marked this PR as `Ready for review` and removed the `[PR] Not Ready for Merge` label. The last thing for us to do is to:
1. Update `Catalog` with latest version and remove `androidGradlePlugin/kotlin` version TODOs.
2. Coordinate the merge wit with all the other library and client PRs, merging this PR only when every other such PR is ready to be merged as well.

**Comment by oguzkocer** [comment]
@ParaskP7 I've updated the dependency catalog to `1.13.0` in 6b7aa4e8e2e139c367250dc30b054cef745d9c8d. I think this PR is ready to merge once we test the clients.

**Comment by ParaskP7** [comment]
> @ParaskP7 I've updated the dependency catalog to 1.13.0 in https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/6b7aa4e8e2e139c367250dc30b054cef745d9c8d. I think this PR is ready to merge once we test the clients.

Awesome @oguzkocer , thanks so much for doing so! 🙇 ❤️ 🚀

**Pull request merged**
