### PR TITLE
Add Observable totalDuration to PagedListWrapper

### PR DESCRIPTION
**Pull request by shiki**
Part of https://github.com/woocommerce/woocommerce-android/issues/3568. 

## What

I added a new `listChanged` observable in `PagedListWrapper` that emits `totalDuration` values. This will be tracked in WC to help gather more information for the slow orders reports (ref p91TBi-4p5-p2). This will also help confirm if whatever we're going to _optimize_ in the future worked. 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/4c8c08780a413f21d529f6a6c9cc175229e9af7d/fluxc/src/main/java/org/wordpress/android/fluxc/model/list/PagedListWrapper.kt#L46-L54

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/4c8c08780a413f21d529f6a6c9cc175229e9af7d/fluxc/src/main/java/org/wordpress/android/fluxc/model/list/PagedListWrapper.kt#L73-L74

### Order IDs Fetching Only

This only tracks the duration of loading the order list summaries via [`FETCH_ORDER_LIST`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/java/org/wordpress/android/fluxc/action/WCOrderAction.java#L41-L42) / [`fetchOrderListSummaries`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt#L123-L136). I thought about including the full `Order` page loads as a whole ([`FETCH_ORDER_BY_IDS`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/java/org/wordpress/android/fluxc/action/WCOrderAction.java#L44-L45)), but it looks like that will result in **incomparable total durations** because we only fetch orders that have not been previously loaded. Example: 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt#L233-L239

So, I think it's better to track consistent fetches like the `fetchOrderListSummaries`. We will only be using the Tracks event to have an idea of how we're progressing as we make changes to the code base and/or API to improve the queries. So I think this will be enough. 

### Total Duration Calculation

image

The total duration calculation is achieved by storing the `requestStartTime` in [`FetchOrderListPayload`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt#L50-L54) and passing it through [`FetchOrderListResponsePayload`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt#L71-L85). `FetchOrderListResponsePayload` eventually leads to dispatching `FETCHED_LIST_ITEMS` with a [`FetchedListItemsPayload`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/store/WCOrderStore.kt#L573-L583). `ListStore` will [receive this event](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/fluxc/src/main/java/org/wordpress/android/fluxc/store/ListStore.kt#L261-L265), **calculate** the total duration, and emit an `OnListChanged`. This is received by `PagedListWrapper` which [emits a value through the `listChanged` `LiveData`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/fluxc/src/main/java/org/wordpress/android/fluxc/model/list/PagedListWrapper.kt#L144) that we can observe and add the tracking in: 

 https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b9aed61a63105839b2a4656d242e3f19d8a9f5/example/src/main/java/org/wordpress/android/fluxc/example/WCOrderListActivity.kt#L146-L151

## Testing

1. Please use the branch in https://github.com/woocommerce/woocommerce-android/pull/3635
2. Log in and navigate to the Orders list → Processing. Pull to refresh.
3. Confirm that there is a log like this:
    ```
    🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.148,"status":"processing","blog_id":171751943,"is_wpcom_store":false}
    ```
4. Navigate to All Orders. Pull to refresh.
5. Confirm that there is a log like this:
    ```
    🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.148,"status":null,"blog_id":171751943,"is_wpcom_store":false}
    ```
5. Scroll down so the next set of Orders is loaded. Make sure you have lots of orders though. 😅 
5. Confirm that there is a log like this:
    ```
    🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.148,"status":null,"blog_id":171751943,"is_wpcom_store":false}
    ```
6. Tap on Search and pick the Completed status. 
5. Confirm that there is a log like this:
    ```
    🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.148,"status":"completed","blog_id":171751943,"is_wpcom_store":false}
    ```

## Author Checklist

- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@shiki This PR looks good to me, but it does touch some shared WordPress code so I'd like to get a second opinion from @oguzkocer as this is his brain child and he understands this code better than anyone else. Nice job documenting this PR btw 👍

**Comment by oguzkocer** [comment]
@shiki Unfortunately I can't get to this today, but I'll do my best to get to it tomorrow. Sorry about that!

**Comment by shiki** [comment]
Talked with Oguz about this today. We agreed that we don't need to have the `LiveData`. I can use an event in `WCOrderStore` instead and track that. I'll make the changes later.

**Comment by shiki** [comment]
@oguzkocer This is now ready for another look. 🙏 

I also updated https://github.com/woocommerce/woocommerce-android/pull/3635/ if you'd like to see how it's going to be used.

**Review by oguzkocer — COMMENTED** [review]
@shiki This looks much better to me compared to the previous iteration. It's now much more self-contained.

I realize this is not something we discussed on the previous call, but I was wondering it'd make sense to only track the network time instead of the whole flow. That'd further simplify the code, but more importantly, the data itself **may** be more useful. (totally up to you)

One minor concern I have is the name for `OnOrderSummariesFetched`. I wonder if it may cause any confusion on the client side for the uninitiated. Mainly, I wonder if anyone would expect any data to be in that event. Not sure if it's worth changing the name, but I thought I'd bring it up.

Aside from these minor questions, it's a 👍 from me. Please feel free to ping me again for a review or work with a WCAndroid developer to get this merged if I can't get to it quickly.

**Comment by shiki** [comment]
Thanks for checking this, @oguzkocer. 

> I was wondering it'd make sense to only track the network time instead of the whole flow.

Right, this only includes the network call now. It'd be useful if we can include the time it takes to persist the items in the database. But if I'm understanding the logic correctly, that would mean I would need to emit the event within [`ListStore.handleFetchedListItems`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e2bea46245466980477e1776c686ef7c88bddd34/fluxc/src/main/java/org/wordpress/android/fluxc/store/ListStore.kt#L224-L261), right? If so, would that be okay with you? 

Is it okay if I add `requestStartTime` back to the `OnListChanged`? And then maybe I can catch that event in `WCOrderStore` and emit `OnOrderSummariesFetched` when we receive `OnListChanged`. 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e2bea46245466980477e1776c686ef7c88bddd34/fluxc/src/main/java/org/wordpress/android/fluxc/store/ListStore.kt#L259

I don't want to touch `ListStore` if that's not ideal. It's okay to not have the database persistence too since we already have a few tracking built (p91TBi-4FI-p2) and this is just one of the data points that we can use. 

> One minor concern I have is the name for OnOrderSummariesFetched. I wonder if it may cause any confusion on the client side for the uninitiated. 

I didn't recognize that as something concerning. Do you have a suggestion for a better name?

**Review by oguzkocer — APPROVED** [review]
> I don't want to touch `ListStore` if that's not ideal. It's okay to not have the database persistence too since we already have a few tracking built (p91TBi-4FI-p2) and this is just one of the data points that we can use.

To answer all 3 questions about `ListStore`, I definitely do not mind making any necessary changes to these classes. If you believe any change to be for the best, I think you should go ahead with it.

In this particular case, I personally don't see enough value in tracking the DB writes, as they shouldn't be anything different. The only DB interaction that's a bit different is the reads, because that happens more often than a typical store, but even that in itself is unlikely to be an issue. As mentioned on the call, if the diff callbacks are not calculated in the BG thread, that could be a cause of lagginess, but that information wouldn't be anywhere in `ListStore`.

However, that's just my opinion. If you feel differently about this, by all means, please go ahead and add anything you need. If you do make the change, I suggest trying to keep it as isolated as possible and consider removing it if it doesn't prove useful.

> I didn't recognize that as something concerning. Do you have a suggestion for a better name?

I've thought about this when I did the review, but couldn't come up with a good one unfortunately :(

> Right, this only includes the network call now.

Well, that's not 100% correct, and I was kind of suggesting the opposite route to you in my review by isolating the tracking to `OrderRestClient.fetchOrderListSummaries` by basically starting the timer at the beginning of the method and finalizing at success and failure callbacks. The reason I suggested this was, the tracking currently includes the EventBus actions and some extra code, so quickness of the device will come into play. That's more than likely a very negligible difference, but considering it'd have made the code even more isolated, I thought it was worth considering.

**Comment by shiki** [comment]
> Well, that's not 100% correct, and I was kind of suggesting the opposite route to you in my review by isolating the tracking to OrderRestClient.fetchOrderListSummaries by basically starting the timer at the beginning of the method and finalizing at success and failure callbacks. 

Oh, god. You're right. I can't believe I did not realize that. Clearly, I'm out of practice with FluxC. 



---

Thanks for approving this. I think at this stage, it's okay to keep this as-is. So I'll merge it no matter how embarrassed I am with this implementation. 😅 We'll consider adding more tracking or update this if we realize later that we'd need more information.

**Pull request merged**
