### PR TITLE
[Detekt Baseline Warnings] Plugins Woo Commerce Module - Resolve/Suppress Style Warnings

### LINKED ISSUE #2486: Resolve/Suppress Detekt Baseline Warnings - Plugins Woo Commerce Module
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `plugins:woocommerce` module.

Number of Warnings: `200`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2494
    - style (`52`) ✅
        1. DataClassShouldBeImmutable (`3`) ✅
        3. ForbiddenComment (`6`) ✅
        4. MagicNumber (`15`) ✅ (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103#issuecomment-1211868401), cc @anitaa1990 @AmandaRiu )
        5. MaxLineLength (`9`) ✅
        6. ReturnCount (`13`) ✅
        7. SpacingBetweenPackageAndImports (`1`) ✅
        8. UnnecessaryAbstractClass (`2`) ✅
        9. UnusedPrivateMember (`1`) ✅
        10. UseCheckOrError (`2`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2498
    - complexity (`37`) ✅
        1. ComplexCondition (`1`) ✅
        2. ComplexMethod (`10`) ✅
        3. LargeClass (`4`) ✅
        4. LongMethod (`10`) ✅
        5. LongParameterList (`6`) ✅
        6. NestedBlockDepth (`6`) ✅
    - naming (`99`) ✅
        1. ConstructorParameterNaming (`9`) ✅
        2. MemberNameEqualsClassName (`1`) ✅
        3. VariableNaming (`89`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2506
    - empty-blocks (`1`) ✅
        1. EmptyFunctionBlock (`1`) ✅
    - exceptions (`4`) ✅
        1. SwallowedException (`2`) ✅
        2. TooGenericExceptionCaught (`2`) ✅
    - performance (`6`) ✅
        1. ArrayPrimitive (`2`) ✅
        2. SpreadOperator (`4`) ✅
    - potential-bugs (`1`) ✅
        1. ImplicitDefaultLocale (`1`) ✅

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2479
Partially Closes: #2486

This PR resolves/suppresses all `style` related warnings for the `plugins:woocommerce` module:

1. `3` x DataClassShouldBeImmutable (Resolve: 8a526d4ab273cdaf9dcc5cc8e3b1383e8375de5a + 44788816a8ce9d79b2dc4b7768662dd8bae8141f)
2. `6` x ForbiddenComment (Suppress: b7466eee836f7cb2ec1d4cdce174a8c490614cd8)
3. `15` x MagicNumber (Resolve: f55ad6e65a38b9eea888b3b91ee9a02a86e5ba01 + Suppress: c33859f36ade917667213484c86b8e255d777b64 + Question [❓]: [see comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103#issuecomment-1211868401) @anitaa1990 @AmandaRiu)
4. `9` x MaxLineLength (Resolve: 5d6b66222333d6410317cfc0c8b04c32c3db7044 + Suppress: 7097dc2af36808c427132075a85486990d3248a4)
5. `13` x ReturnCount (Resolve: c700ef6f7945ff6b739346e259b490412fc03d33 + Suppress: 2e9394667112549e535a3cb165d510f9fab5bf09)
6. `1` x SpacingBetweenPackageAndImports (Resolve: 6dcca837a736ada45008ad8f9dc22b931a8a126d)
7. `2` x UnnecessaryAbstractClass (Resolve: 377e3ca9ff7d9208a81b05d88bbde0fe13ddf9ca)
8. `1` x UnusedPrivateMember (Resolve: 6871985de7f76ba4f137fc6a3dd55c23c5c4135a)
9. `2` x UseCheckOrError (Resolve: 1594872df7959dab2af33114b5ff253ce9934e9c + Suppress: 5236ee56acb95d259a0027c4eef47a074de04e02)

PS.1: I am randomly adding an engineer from the WCAndroid team as the main reviewers, that is, in addition to the @wordpress-mobile/owl-team team itself, since I just want someone from that team to sign-off on that change as well (or additionally to the 🦉 team).

PS.2: I recommend reviewing this PR commit-by-commit.

-----

To test:

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough (especially the `detekt` check).
- However, if you really want to be thorough, you could smoke test the `example` and/or the `WCAndroid` apps to verify that everything works as expected.

PS: Please ignore the failing `connected-tests` check as they are unrelated to this PR. This check has been failing consistency for some time now due to tests being flaky or needing to be updated/fixed.

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @atorresveiga and apologies for the extra ping! 🏓 

This is just a friendly reminder as this PR is still pending review. Let me know if you can still review it, or if you don't have the capacity to do so at the moment, and I'll make sure to assign this to someone else, no worries! 👍 💯

**Review by atorresveiga — APPROVED** [review]
Great work, @ParaskP7!
Everything looks good to me. :shipit:
One quick note: When I tried to smoke tests the app using this branch with `trunk` of Woo I was having conflict with the `NotificationModel` being immutable, a change that I presume is related to `DataClassShouldBeImmutable`, even though the change was not part of this PR. This is just a heads up, because there may be a PR on Woo that needs to be merged

**Comment by ParaskP7** [comment]
👋 @atorresveiga !

Thank you so much for the review and testing! 🥇 🙇 🌟 

> One quick note: When I tried to smoke tests the app using this branch with trunk of Woo I was having conflict with the NotificationModel being immutable, a change that I presume is related to DataClassShouldBeImmutable, even though the change was not part of this PR. This is just a heads up, because there may be a PR on Woo that needs to be merged

Thanks so much for the heads-up! 🙏

I'll now go ahead and merge `trunk` to this PR now, resolve any conflicts that this might produce and then, if CI completes successfully, I'll merge this to `trunk`. 💯

**Comment by ParaskP7** [comment]
👋 @atorresveiga !

> I'll now go ahead and merge trunk to this PR now, resolve any conflicts that this might produce and then, if CI completes successfully, I'll merge this to trunk. 💯

Just an FYI, I didn't get any merge conflicts with `trunk`,thus I might have misinterpreted the problem you were having with the `NotificationModel` being immutable change, which is related to this 8a96a86fb723285d8a056231ebad6096231aadd9 commit. Can you help me understand this quick note of yours and whether I should progress with this merge? 🤔

**Comment by atorresveiga** [comment]
>I didn't get any merge conflicts with trunk

 Sorry @ParaskP7 I don't mean a merge conflict, just an error on [this line](https://github.com/woocommerce/woocommerce-android/blob/4816d98204e8dfcd351e665a24180d2dec939777/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt#L63) because of the `NotificationModel` being immutable, so wanted to warn you about that 
 
  >I should progress with this merge?
  
  Yes, sure :shipit:

**Comment by ParaskP7** [comment]
> Sorry @ParaskP7 I don't mean a merge conflict, just an error on [this line](https://github.com/woocommerce/woocommerce-android/blob/4816d98204e8dfcd351e665a24180d2dec939777/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt#L63) because of the NotificationModel being immutable, so wanted to warn you about that

Ah I got it now @atorresveiga ! 💯 

What you are saying is that when WCAndroid (or WPAndroid for that matter) will start using the new version of `FluxC`, this problem on [this line](https://github.com/woocommerce/woocommerce-android/blob/4816d98204e8dfcd351e665a24180d2dec939777/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/reviews/ReviewDetailRepository.kt#L63) and any other such problem will need fixing, right? 🤔 

In that case, I think this is (kind of) expectable, right? The clients should now use a `copy` function instead. But, on the other hand, if we where required to revert this change on the `FluxC` side (like suppressing it instead), just because the client does indeed need the previous version of the code (as it was before), then we would have needed to first update `FluxC` and then update it on the client's side, which wouldn't be ideal, that's what you was worried about in the first place, right? 🤔  

> Yes, sure :shipit:

🙏

**Pull request merged**
