### PR TITLE
Fix #524: fix XMLRPC serialization issue

### LINKED ISSUE #524: XMLRPC serializer crashes on some emoji (chars out of the XML v1.0 spec)
Try to upload a post containing `😆` on a self hosted site to repo.

### PR DESCRIPTION
**Pull request by maxme**
Fix #524: fix XMLRPC serialization issue

* `git checkout  fc4af79 && ./gradlew test` 💥 (176 tests completed, 1 failed)
* `git checkout issue/524-fix-serialization-issue && ./gradlew test` 🍸 🍺 🍷

### CODE REVIEW

**Comment by maxme** [comment]
When this is merged, would be great to update the hash dependency in wpandroid `release/7.9`.

**Comment by aforcier** [comment]
We're still going to get an error log every time a post contains an offending emoji [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/445579994301a6f7e50c4ffb6c94e66585699712/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCSerializer.java#L179), should we maybe step that down to a debug log without a stack trace?

**Comment by aforcier** [comment]
Confirmed the fix with the test and with uploading a post containing 😆 before and after 👍.

**Comment by maxme** [comment]
> should we maybe step that down to a debug log without a stack trace?

Yeah good point, same for the other log, I'll make it a warning only.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
