### PR TITLE
[Nullability Annotations to Java Classes] Add Missing Nullability Annotations to `Discovery` Network Client Classes (`safe`)

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2798

This PR adds any missing nullability annotation to [DiscoveryWPAPIRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/3caf1058bd9384da8a134cee9855c92e31e7ff5f/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/DiscoveryWPAPIRestClient.java#L4) and [DiscoveryXMLRPCClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/3caf1058bd9384da8a134cee9855c92e31e7ff5f/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/DiscoveryXMLRPCClient.java#L4), all its related response classes and anything in between (ie. `AccountStore`, `SiteWPAPIRestClient`).

FYI.1: This change is `safe`, meaning that there shouldn't be any (major) compile-time changes associated with this change. Having said that, testing is highly recommended since the changes in this PR can affect one or more clients (ie. [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android), [WCAndroid](https://github.com/woocommerce/woocommerce-android), etc)

FYI.2: An analysis on `AccountStore`, `SiteWPAPIRestClient` and their usages with our main clients suggests that this store is being utilizing by both, the [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android) and [WCAndroid](https://github.com/woocommerce/woocommerce-android) clients.

-----

PS.1: @hichamboushaba I added you as the main reviewer, randomly so, since I just wanted someone from the WooCommerce mobile team to be aware of and sign-off on that change for both. Feel free to merge this PR directly yourself if you deem so.

PS.2: @irfano I am also adding you as an extra reviewer, randomly so, since I want someone from the Jetpack/WordPress mobile team to be aware of this change as well. However, there is no need for you to review it as well, thus duplicating the review work. Having one team member from either of the mobile teams reviewing and testing this change is enough for this change.

-----

Nullability Annotation List:

1. [Add missing n-a to discover base url on discovery rest client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/2124dcf3c05a2f8da73f68f2ace65ec7686ea051)
2. [Add missing n-a to verify support on discovery rest client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/609c00f0ab263a1267b65610f0af9c017827a3ea)
3. [Add missing n-a to get response on discovery xmlrpc client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/7b8794992e80e2da4229e5bb9882e252ffbdedb9)
4. [Add missing n-a to list methods on discovery xmlrpc client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/15b8b431b8503f0e29f32e114cc2be7b6c3eb21d)
5. [Add missing nn-a to dispatcher field on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/d269f056ad6bba4aa234e13d8ca889ab58c003df)
6. [Add missing nn-a to xmlrpc client field on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/aa25c2b53579b4cb53f6318b85934eefb6e5f36c)
7. [Add missing nn-a to rest client field on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/947d25d3128b83538b30a4657dccb7008e45bab3)
8. [Add missing n-a to discovery exception on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/ec03e8b2c314090188d3f2a7114770b8bc1d73a2)
9. [Add missing n-a to find endpoint on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/9d2374eef746f637bb1e0103eb90c4395db58cbc)
10. [Add missing n-a to ordered verify urls to try on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/258c459f662458592f7b5c272a9c832c25269783)
11. [Add missing n-a to rsd metal tag href regex on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/ae9d0aceb9bc979c435d044904b9edf6045cfe29)
12. [Add missing n-a to sanitize site url on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/441205da6cb21efd2ee9f125f15a141b8556deb5)
13. [Add missing n-a to check xmlrpc ep validity on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/a4880a202aabcf71be6d56a18b874797d14b15e5)
14. [Add missing n-a to discovery result payload on sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/304dda36c3f6dbf7d7bf43657f77a9e089ceb229)
15. [Add missing n-a to strip known paths on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/f055d801bd08f9a256f51c4a00f726b53231cbb8)
16. [Add missing n-a to validate lm response on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/3534b59a99121bab0dc9282a8a5212e92da22541)
17. [Add missing n-a to is http auth em on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/a318e36083c39b81348e5c101e36696ef4219757)
18. [Add missing n-a to get xmlrpc api link on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/3ffcd6361c8cf87f02a7c954c10827b040f43d0e)
19. [Add missing n-a to get xmlrpc pingback on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/a5f001745d142b7e15fa4e9e222a3f5e1a05c254)
20. [Add missing n-a on discovery xmlrpc request](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/d966a54792acc3797456cfdb540fd5943fed2f78)
21. [Add missing n-a on discovery request](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/eef4c1080aaaf3bbe8e5e0dacaf2e75cde1478f4)
22. [Add missing n-a on wp api head request](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/1b547e52a11cfd5b70cb227d79f75dcac377fd74)

Nullability Checks List:

1. [Guard usages of response namespaces on discovery rest client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/ded97e474af743fe94bd71e35eaea79b6ffeb7df)
2. [Guard usages of response headers on wp api head request](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/2637e6a0d6ef9ef89831cec123e262f0dc7cfc68)

Warnings Resolutions List:

1. [Remove discovery exception from discover base url throws list](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/6433ad2fb054d43694e1da39d7213f4a0cdd9748)
2. [Change type of request to root wp api rest response](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/a1d7fb577337764751c277ea8c3a09de31c72d28)
3. [Remove discovery exception from rsd url based throws list](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/3121ba97e84ce52c99e9dae1a4eec1cf25d25eed)

Warnings Suppression List:

1. [Suppress commented out code on discovery rest client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/331faf79a36f8dc1caa4ab98a9d17cba771e07af)

Refactor List:

1. [Reformat discovery wp api rest client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/44462cadf416113029ff6562a94e18cbde3191c6)
2. [Reformat discovery xmlrpc client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/bf88d6c9a3061c2cf991af4c8c0710d5dea9d6c4)
3. [Reformat self hosted endpoint finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/f76c5fa566de2f28e9fbd96241199acbd7b003c1)
4. [Replace anonymous classes with lambda](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/7612739229e6cdbd97f23cae57268ac895a41c91)
5. [Move static rsd link field to top of sh ep finder](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/e7b3709e8bc8090637d9cadb6cd836b591e983c6)

Docs List:

1. [Fix typo with perform on discovery xmlrpc client](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/859cca25d5844ae8b870dd9efb8724c4105378eb)
2. [Fix typo with perform on discovery utils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2872/commits/97370bd7fab48613e7ac01fe1aa564e955c91449)

-----

## Associated Clients

It is highly recommending that this change is being tested on the below associated clients:

- [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android)
- [WCAndroid](https://github.com/woocommerce/woocommerce-android)

-----

## To Test (`REST`):

- Smoke test the `FluxC Example` app via the `SIGN IN & FETCH SITES`, `SIGH OUT` & `SIGNED OUT ACTIONS` screens. Verify everything is working as expected.
- In addition to the above, using [local-builds.gradle](https://github.com/wordpress-mobile/WordPress-Android/blob/44a6d0611175f132ff6920b4d6a3e16d565259b6/local-builds.gradle-example#L18) on [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android), smoke test any login/out and fetch site related functionality on both, the WordPress and Jetpack apps, and see if everything is working as expected.
- Furthermore, using [local-builds.gradle](https://github.com/woocommerce/woocommerce-android/blob/trunk/local-builds.gradle-example) on [WCAndroid](https://github.com/woocommerce/woocommerce-android), smoke test any login/out and fetch site related functionality and see if everything is working as expected.

## To Test (`XMLRPC`):

- Create a new self-hosted WordPress site for XMLRPC testing purposes ([jurassic.ninja](https://jurassic.ninja/)).
- Smoke test the `FluxC Example` app via the `SIGN IN & FETCH SITES`, `SIGH OUT` & `SIGNED OUT ACTIONS` screens. Verify everything is working as expected.
- In addition to the above, using [local-builds.gradle](https://github.com/wordpress-mobile/WordPress-Android/blob/44a6d0611175f132ff6920b4d6a3e16d565259b6/local-builds.gradle-example#L18) on [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android), smoke test any login/out and fetch site related functionality on both, the WordPress and Jetpack apps, and see if everything is working as expected.
- Furthermore, using [local-builds.gradle](https://github.com/woocommerce/woocommerce-android/blob/trunk/local-builds.gradle-example) on [WCAndroid](https://github.com/woocommerce/woocommerce-android), smoke test any login/out and fetch site related functionality and see if everything is working as expected.

### CODE REVIEW

**Review by hichamboushaba — APPROVED** [review]
Nice work @ParaskP7, thanks for handling this.
I reviewed the code, and I tested the changes with WCAndroid, and there are no compile errors.

**Comment by ParaskP7** [comment]
👋 @hichamboushaba and thanks so much for reviewing and testing this, you are awesome! 🙇 ❤️ 🚀 

FYI: @irfano I'll be also waiting any input from you, else a quick 👍, that is before proceeding with merging this, just so that I know you are aware of this change merging into `trunk` before it happens.

**Review by irfano — APPROVED** [review]
I conducted smoke tests on signing in, signing out, and site-fetching screens for WordPress.com and a self-hosted site. Everything appears to be working fine 🟢.
I also skimmed the code changes; they all seem safe.

**Comment by ParaskP7** [comment]
Awesome, thank you so much for the skim review, testing and merging this @irfano , you rock! 🙇 ❤️ 🚀

**Pull request merged**
