### PR TITLE
Add details about OAuth2

### PR DESCRIPTION
**Pull request by drspaceboo**
This PR updates the README file to add some more details regarding OAuth2. Specifically pointing people to the page where they can get those details.

### CODE REVIEW

**Comment by aforcier** [comment]
@jtreanor it looks like the mocked connected test task on CircleCI for this PR is failing - I suspect it's to do with the Firebase config and the branch being from a fork? I think I recall us running into something like this before.

**Comment by jtreanor** [comment]
@aforcier yeah, unfortunately Frirebase tests won’t work for forks. There’s no easy way to avoid that unfortunately but we should definitely make it fail with a more helpful message

**Comment by drspaceboo** [comment]
Tests can probably be ignored give that the PR only changes the README

**Comment by AmandaRiu** [comment]
@jtreanor this all looks good for merge, but I'm unable to do it due to the failed tests. Any recommendations?

**Pull request merged**
