### PR TITLE
Add an optional task to CI to run connected tests

### PR DESCRIPTION
**Pull request by oguzkocer**
**To test:**

Approve the optional tests job from [here](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/4534/workflows/8d702759-fb12-49d5-b1ab-01750b1af53a) and verify that it succeeds.

### CODE REVIEW

**Comment by loremattei** [comment]
The changes look good to me and they started the optional tests as expected, but the tests are failing 🤔. 
There's something which puzzles me: looking at the diff shown by GitHub, it looks like this PR only adds the configuration to run the tests on demand, but checking the file in this branch against the one in `develop`, it seems the PR also adds back the tests themselves which are currently commented out in develop 🤔.

@oguzkocer  I'm not totally sure what I'm missing 😅

**Comment by oguzkocer** [comment]
@loremattei This is happening because this branch is quite old. I'll merge `develop` into it once we enable the connected tests again.

**Comment by loremattei** [comment]
Ah! Ok! Got it now: the connected tests have been commented out after this branch was cut. 
So, since this PR is only about the optional task, I'm approving it as it works as expected 👍

**Review by loremattei — APPROVED** [review]
:shipit:

**Pull request merged**
