### PR TITLE
Feature/what new endpoint

### PR DESCRIPTION
**Pull request by khaykov**
This PR adds some additional functionality, like caching and ability to call suspended store methods directly to the WhatsNew Store developed by @develric 

Can be tested with [this](https://github.com/wordpress-mobile/WordPress-Android/pull/12205) wpandroid PR.

### CODE REVIEW

**Review by develric — APPROVED** [review]
I tested this one using the WPAndroind companion PR and works as expected. Also code LGTM 👍 .

**Comment by ParaskP7** [comment]
👋 @khaykov @develric !

It's been 2 years already, I know... 😅 But, let me ask you this coroutines related question below, just in case you still remember the answer. 🤞 

As part of [this Detekt related issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2485) that I am currently working on, I am trying to resolve the `GlobalCoroutineUsage` related warnings. To that end, the only `2` warnings that I am seeing, that is, on the `fluxc` module, are related to this [WhatsNewStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/store/WhatsNewStore.kt) store that you both worked on (see [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/store/WhatsNewStore.kt#L41) and [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/store/WhatsNewStore.kt#L51)). Was there a reason you used the `GlobalScope.launch(coroutineContext) { ... }` alternative in favor of the usual suspect, the `coroutineEngine.launch(AppLog.T.API, this, "ACTION_TYPE") { ... }`? 🤔

**Comment by khaykov** [comment]
Hey @ParaskP7 👋 I don't remember exactly, but given that it was 2 years ago, there was probably no specific reason and we didn't I assume we just didn't know better at the time :)

**Comment by ParaskP7** [comment]
👋 @khaykov ! 😄 

Thank you so much for the reply and for providing some more context on top of that. You are helping me making the decision of replacing the `GlobalScope` and that's enough for me for now. Thus, I very much appreciate that! 🙇

**Pull request merged**
