### PR TITLE
Self hosted media upload issues

### LINKED ISSUE #257: Uploading media not working correctly for self-hosted sites
We have had multiple issues while working on the Instaflux demo app for self-hosted media upload. First of there is a `NullPointerException` in `MediaXMLRPCClient.notifyMediaUploaded` because `media` can be `null`. Furthermore, we want the same developer experience for both .com and self-hosted sites, so if the media object can not be constructed from the media upload request, we should be doing a fetch request for that media and send it instead.

Some related comments and commits below:
https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/252#issuecomment-268458687
https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/252#discussion_r93396419
https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/252/commits/2054c324b8c8bc1ab4aacfde3b0c54fdba8cc40b

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #257. I think this is pretty much the change set we need to fix the issue, with only thing lacking is the error handling for the fetch request which I don't know how to approach. However, on my self-hosted site https://oguzkocer.wpsandbox.me even though the upload request finishes with 200, the media never ends up in my library. I couldn't find why, @tonyr59h do you mind taking a look at this one?

About the fetch error, I don't think we can re-upload the media as @maxme suggested before, because we would end up with duplicate. We can try a re-fetch, but I think we'd need some kind of error handling for "successful upload but unsuccessful fetch" no matter what we do.

P.S: I am opening an early PR so we have somewhere async to discuss these 2 issues, thanks!

### CODE REVIEW

**Comment by oguzkocer** [comment]
@tonyr59h any progress on this one?

**Comment by tonyr59h** [comment]
> any progress on this one?

Not yet, I think the kinks have been worked out of uploading on the integration branch though. I'll give this another shot in the morning.

**Comment by oguzkocer** [comment]
@maxme This is the best solution I could come up with so far. Once upload completes with a `200` and we can't parse the response, we do a fetch and either return an error or a success for the `upload` event (not the fetch). I have also fixed several small stuff (or made some improvements).

Unfortunately getting `200` from the xml-rpc endpoint doesn't mean much as my self-hosted uploads are still failing. I think we need to separate that to another issue, I am just not sure how to fix that yet.

Once this is merged I'll open that issue if that's OK with you.

**Comment by maxme** [comment]
@oguzkocer there is a problem [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9c965f6acedbe3b24cf9e20b980b4606d21f968c/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java#L165-L166) because `getMediaFromUploadResponse()` generate an almost empty media model, I think we have to fetch uploaded media in every cases for XMLRPC calls, we can't count on the upload response.

**Comment by maxme** [comment]
I mean do something like:
```diff
--- a/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java
+++ b/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java
@@ -163,13 +163,7 @@ public class MediaXMLRPCClient extends BaseXMLRPCClient implements ProgressListe
                 if (response.code() == HttpURLConnection.HTTP_OK) {
                     AppLog.d(T.MEDIA, "media upload successful: " + media.getTitle());
                     MediaModel responseMedia = getMediaFromUploadResponse(response);
-                    if (responseMedia != null) {
-                        responseMedia.setLocalSiteId(site.getId());
-                        responseMedia.setId(media.getId());
-                        notifyMediaUploaded(responseMedia, null);
-                    } else {
-                        fetchMedia(site, media, true);
-                    }
+                    fetchMedia(site, responseMedia, true);
```

**Comment by oguzkocer** [comment]
> @oguzkocer there is a problem here because getMediaFromUploadResponse() generates an almost empty media model, I think we have to fetch uploaded media in every cases for XMLRPC calls, we can't count on the upload response.

@maxme Is the media uploading for you at all? The response is `null` for me too, but it never uploads and there was some kind of error hidden in the `body` of the `response`. If it's not uploading for you either, we should wait for that change as the `response` might get fixed if we can fix the `request`.

**Comment by maxme** [comment]
Upload works, but we must fetch the media in all cases to update fields like "fileUrl" or "title".

**Comment by oguzkocer** [comment]
That's interesting, I wonder why it's not working for me. I'll update the code as you suggested.

**Comment by maxme** [comment]
> I'll update the code as you suggested.

Wait 10 mins, I'm testing a branch

**Comment by oguzkocer** [comment]
> Wait 10 mins, I'm testing a branch

Sure, I am deep in another branch right now anyway. It might take a bit of time for me to update. Feel free to change it and I can review if you want :)

**Comment by maxme** [comment]
I pushed f0d1070 and f90f158, they fix the issues I was getting (uploaded image was not fetched and when it was the local id was different after save).

**Comment by oguzkocer** [comment]
> I pushed f0d1070 and f90f158, they fix the issues I was getting (uploaded image was not fetched and when it was the local id was different after save).

Sounds good @maxme, if there is no rush, I'll take a look at the changes and test them later. I assume other changes are good, so we can :shipit: if these last changes work?

**Comment by maxme** [comment]
Yes, other changes look good!

**Comment by maxme** [comment]
Note: I tried this branch in wpandroid and was able to upload media from the editor.

**Comment by oguzkocer** [comment]
Your changes looks good @maxme :shipit: Feel free to merge after travis is done!

**Pull request merged**
