### PR TITLE
Fetching an empty list of posts should mark canLoadMore posts as false

### LINKED ISSUE #1481: Post List - canLoadMore doesn't work as expected for contributors
I think this bug might be related to [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1475) change.

When I scroll down on Post List Search, the app keeps trying to load more items indefinitely even though there aren't any items to load.

Steps to reproduce:
1. Login and switch to a site where you are in the contributor role (*I think a couple of other conditions need to be met)
2. Open PostList
3. Click on Search
4. Type [search_query]
5. Scroll down
6. Notice the list keeps fetching more items indefinitely

gif
a
b

I have a guess what is happening under-the-hood.
There 57 results for the [search_query], but the user has access only to 27 of them since they are in contributor role. 
Notice the request is `offset=20` and the result contains `7` posts but the `found` attribute is `57` => `boolean canLoadMore = response.getFound() > offset + postListItems.size();` is evaluated to `true` and we try to load more items again and again and again.

*Conditions I think need to be met
1) user is in contributor role
2) the blog contains at least one post which the user doesn't have an access to
3) the search query matches the post from condition `2`

All in all it seems like a bug in the API -> I don't think `found` should return number of posts on the blog matching the query but only the number of posts matching the query the user has an access too. Wdyt? cc @oguzkocer

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #1481. Although #1481 is an API issue, which I'll report soon, there is an easy way for us to fix the issue in the client side. We simply set `canLoadMore` to `false` if we get an empty response. I think that's an OK thing to do by itself, so even if the API is fixed, I wouldn't mind having this in the code as a fail-safe for other API issues we might be unaware of.

**To test:**
Perform the tests outlined by @malinajirka in #1481 in WPAndroid for `issue/fix-can-load-more-for-fetching-post-list-2` [branch](https://github.com/wordpress-mobile/WordPress-Android/tree/issue/fix-can-load-more-for-fetching-post-list-2):

```
1. Login and switch to a site where you are in the contributor role (*I think a couple of other conditions need to be met)
2. Open PostList
3. Click on Search
4. Type [search_query]
5. Scroll down
6. Notice the list keeps fetching more items indefinitely
```

@malinajirka I don't currently have a site setup to test this, do you mind checking if you can reproduce the issue in this branch? Thanks!

### CODE REVIEW

**Comment by malinajirka** [comment]
Hmm, it seems there is another issue. The app keeps requesting "offset=20" and the server keeps returning 7 items => therefor the fix doesn't have any effect. Moreover, it seems the 7 items are never shown on the UI. I'll dm you credentials to my testing account or let me know and I can look into it tomorrow.

**Comment by oguzkocer** [comment]
@malinajirka Unfortunately this is due to yet another API issue. The problem here is that when we do the initial search and we pass `60` as `pageSize`, the API returns:

_Note that the responses are shortened and only the post IDs are included to make it easier to follow along._
```
found: 70
posts: [663, 636, 634, 633, 630, 629, 628, 627, 626, 625, 620, 619, 617, 603, 599, 598, 597, 594, 591, 575]
```

There are 2 problems here:
1. The `found` property is not correct (which is what this PR was trying to address)
2. Even though we request `60` posts, it returns `20` posts (it turns out this is because there are only 20 posts, read on for details)

Now, from this response, we think there are more posts to be fetched. So, we make another request with the offset `20` because that's how many items we got and this is the response:

```
found: 57
posts: [603, 599, 598, 597, 594, 591, 575]
```

Again, there are 2 problems:
1. Same issue as above, found property `57` is incorrect. Not only that, it doesn't event match the previous request.
2. This one is less obvious. Notice that even though we get 7 IDs in the second response, all of them were already included in the initial response. This is why the app only displays 20 posts, because there are no new posts fetched. However, since the response says there are more posts and it keep returning the same set of IDs because we keep sending the same offset which is because we get no new posts, it gets into this infinite loop.

---

On the client side, we _could_ adress this by checking if the requested page size and the returned posts size match and if it doesn't we could assume there are no more posts to fetch. I don't feel as good about it as I did with this PR though because that'd be a bigger assumption to make. In any case, at this point it might be best to see what will happen with the API first.

**Comment by oguzkocer** [comment]
@malinajirka I think we should merge this PR since this is still a positive change for how we check if there is more data to be loaded. We can still keep the issue open since we'll need to fix that in the API side and we have a request for that from Platform 9.

**Comment by malinajirka** [comment]
@oguzkocer I might be missing something, but I'm not sure it's a positive change. 
- Before this fix, we were showing all the items and the app looked like it's loading more. 
- After the fix the app doesn't show all the items and it seems it's loading more. 

Wdyt?

**Comment by oguzkocer** [comment]
> - Before this fix, we were showing all the items and the app looked like it's loading more.
> - After the fix the app doesn't show all the items and it seems it's loading more.

@malinajirka All we are doing in this PR is verify that we at least got some results when we request posts. In worst case scenario, it shouldn't have any effect.

Let's say we requested posts with an offset of `50` and we didn't get any results, when we next make the request, we'll still have `50` as its offset, so we'll just replicate the same call and won't get any results. Simply put, we need to get some results back in order to be able to make a new request.

In this specific case, as explained in a previous comment, we actually get some results back but the results we get were already included in a previous request, so the offset doesn't change and we make the same request over and over again. (this is the API issue that needs to be fixed)

---

Just to make sure I am not missing something, which I still might, I re-tested everything with the credentials you provided and I got the exact same result before and after the change. Therefore, I am failing to see in which scenario checking if we got an empty result would have a negative impact. If there is one, I'd really appreciate if you can provide the steps for it, so I can better understand the issue.

**Comment by malinajirka** [comment]
Ohh, you are right. The issue (side-effect of the API bug) on the client side was introduced in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1475, not this PR. Sorry, for delaying this PR.

LGTM

**Pull request merged**
