### PR TITLE
Remove CircleCI Configuration

### PR DESCRIPTION
**Pull request by jkmassel**
We [switched to Buildkite](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2472), now we're removing the old configuration.

I've already deactivated this project in CircleCI, so if CI passes for this PR we should be good to go.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]

**Comment by oguzkocer** [comment]
I am looking into the failed connected tests.

**Comment by oguzkocer** [comment]
@jkmassel I disabled a few tests that were consistently failing for me in 3094e4495ad85418262468ab6ce2e367fd311223. I also changed the Firebase test device to Pixel 3 with API 30 in fe007cfa08cd512773c935700dc6bf124c6f693e, which seems to have fixed most of the tests, but we still have tests failing randomly. I checked the logs in one of the runs and I can see that the test worked but instead of being reported as successful, it `FAILED` somehow at the last second. We could maybe get around this by having retries, but I feel like this is either a Firebase issue or a deep architectural one that we can't feasibly address.

I disabled the requirement for the `buildkite/wordpress-fluxc-android/connected-tests` and I think we should merge this PR as is because it at least makes the tests less likely fail. I'll leave the decision to you.

---

I can't come up with a good short term plan for these failures. I have an idea that I'd like to investigate as a potential project, but it'll be _at least_ a couple months before we can merge anything at that scale. In the meantime the best suggestion I have is to only run these tests in `trunk` and not report them to Github. That way we collect some data in the Buildkite Test Analytics which we can then use in the project to address the issue. We can announce to the developers that we are, at least temporarily, deprecating the connected tests and suggest them to use mocked tests instead.

I am completely open to any other plan as long as we don't block developers, so let me know what you think.

cc @ParaskP7 - I think you should also weigh in on this discussion.

**Comment by ParaskP7** [comment]
👋 @oguzkocer !

Thanks for the ping! 🙏 

> @jkmassel I disabled a few tests that were consistently failing for me in https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/3094e4495ad85418262468ab6ce2e367fd311223. I also changed the Firebase test device to Pixel 3 with API 30 in https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/fe007cfa08cd512773c935700dc6bf124c6f693e, which seems to have fixed most of the tests, but we still have tests failing randomly.

👍 

> I checked the logs in one of the runs and I can see that the test worked but instead of being reported as successful, it FAILED somehow at the last second. We could maybe get around this by having retries, but I feel like this is either a Firebase issue or a deep architectural one that we can't feasibly address.

🤔 

> I disabled the requirement for the buildkite/wordpress-fluxc-android/connected-tests and I think we should merge this PR as is because it at least makes the tests less likely fail. I'll leave the decision to you.

👍 

> I can't come up with a good short term plan for these failures. I have an idea that I'd like to investigate as a potential project, but it'll be at least a couple months before we can merge anything at that scale.

I would love to hear this idea of yours and thanks for looking/thinking about fixing these failures! 🙇 

> In the meantime the best suggestion I have is to only run these tests in trunk and not report them to Github. That way we collect some data in the Buildkite Test Analytics which we can then use in the project to address the issue.

👍 

> We can announce to the developers that we are, at least temporarily, deprecating the connected tests and suggest them to use mocked tests instead.

In general, in favor of mocked tests, so it is a 👍 from my side, but what do you mean by mocked tests? What I mean is, how would a mock test, that would substitute a potential connected test, look like? 🤔

> I am completely open to any other plan as long as we don't block developers, so let me know what you think.

I am 100% onboard with that statement, to not block developers.

As such, this short term plan seems to be valid, especially given the fact that we are going to be thinking more about how to make connected tests more robust, or otherwise, maybe replacing them with mocked tests... 🤔

And this statement of mine, to maybe replacing them with mocked tests, is something I have been also thinking for a while now as I have been seeing more and more flakiness in terms of connected tests. This, obviously is being affected by various reasons (we can discuss them), but still, it is something that has been bothering me (and I bet other engineers) quite significantly I must admit. 😞

**Comment by zwarm** [comment]
My 2 cents: While adjusting the screenshots tests I was seriously thinking about using [WebMockServer](https://github.com/square/okhttp/tree/master/mockwebserver) from square and dropping wiremock. Then using [Barista](https://github.com/AdevintaSpain/Barista) on top of Espresso. We could possibly try this approach with screenshots first and then move on to other tests if we find it reduces flakiness. There is also [Paparazzi](https://github.com/cashapp/paparazzi) from square/block for doing ui testing (really, they just match pixels). I also looked into Mockito alone, but it gets tricky with eventbus.

**Comment by oguzkocer** [comment]
> I would love to hear this idea of yours and thanks for looking/thinking about fixing these failures! 🙇

I'll post an RFC as soon as I can, but it'll likely be a couple weeks from now. I have to flesh out the idea first, so I am reluctant to share details, but it's a design where we'll have one set of external (non-Android) "tests" that hit the real API and save the responses to a repository. Then our tests, both iOS and Android, can use these responses which make them predictable and easier to debug. A rough workflow looks like this:

1. We setup a new account with one or more sites in it, add media/posts etc
2. We use a repo such as `wp-com-test-snapshot` which periodically runs CI jobs
3. We create a, possibly encrypted, config file in this repo with information about login, site id etc.
4. These CI jobs will make calls such as `login`, `fetch-posts`, `upload-media` etc and save the responses
5. Once the CI jobs complete, it opens a PR updating the saved responses with the new ones received in that run. In theory, as long as we discard any current date related information, there shouldn't be a change in the response unless the API has changed.
6. If a PR is raised in this repo, `team-owl` is pinged for a review to see why the API has changed and approve the PR or address the issue.
7. We setup FluxC (or other similar repos) to use the responses saved in the `wp-com-test-snapshot` repo, utilizing the config file from `step 3`. In theory, we might even be able to run an always available mocked server that we can just access with a simple base url change in FluxC, so test setup changes might end up being minimal. If we can't or don't want to use an always on server, we can look into local solutions either using our current setup or one of the alternatives @zwarm mentioned. (thanks for that btw!)

Hope that gives a rough idea of what I am thinking of. I need some time to flesh it out and see if it's a feasible/good solution. There are also some alternatives I'd like to look into before creating the RFC.

> In general, in favor of mocked tests, so it is a 👍 from my side, but what do you mean by mocked tests? What I mean is, how would a mock test, that would substitute a potential connected test, look like? 🤔

We already have mocked tests in the repo, they have the `MockedStack_` prefix, so you can look them up to see how they are currently setup. In short, we use an [interceptor](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/example/src/androidTest/java/org/wordpress/android/fluxc/module/ResponseMockingInterceptor.kt) to return a given `json` as a response instead of actually making a network request. ([example](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/example/src/androidTest/java/org/wordpress/android/fluxc/mocked/MockedStack_PluginTest.kt#L49)) Otherwise, it works similar to our other connected tests. There are some advantages/disadvantages for this setup compared to a full blown mock server.

Using mocked tests network results should in theory make the tests very consistent since it removes the major external variable in these tests. If the issue is Firebase related, even though switching to mocked tests should help, we'll still likely need to make further changes to our setup. My understanding is that we have some plans to drop Firebase, so in that regard I am not sure if a major project now is the way to go. Depending on the timeline for dropping Firebase, maybe we should wait and see how our new setup performs first 🤷

**Comment by jkmassel** [comment]
>I disabled the requirement for the buildkite/wordpress-fluxc-android/connected-tests and I think we should merge this PR as is because it at least makes the tests less likely fail. I'll leave the decision to you.

Agreed. I'm going to merge this – there's a lot of good conversation here I don't want to lose, but I also don't want to unnecessarily block developers. 

So, quickly, @zwarm I think those are all solid ideas, @oguzkocer I think your plan seems interesting though I wonder if we're signing up for the same problems we just got rid of by splitting up the WPmocks repo? It's been my experience that request-level mocking is fundamentally unreliable, that said, I'd be super happy to be proven wrong!! Worth continuing to discuss for sure

**Comment by ParaskP7** [comment]
Fantastic, thank you so much for sharing all this details @oguzkocer , lots to think about! ❤️ 🥇 💯

**Pull request merged**
