### PR TITLE
Remove `instaflux` module

### LINKED ISSUE #2208: Move `InstaFlux` module to separate project
### Motivation

`InstaFlux` is no longer maintained or used. It adds overhead when indexing files in IDE, fetching dependencies or building `FluxC` project.

From times to times it also causes issues (see p1605009939037100-slack-C0QB79UV8).

Let's move it into a different repository.

### PR DESCRIPTION
**Pull request by wzieba**
Closes #2208 

### Description

For motivation, please see #2208 . New repository (for now private) is available here: https://github.com/wordpress-mobile/InstaFlux

It contains all files related to `Instaflux` as well as whole git history of them (extracted via `git filter-repo` tool).
The command I've used is

```shell
git filter-repo --path fluxc --path fluxc-annotations --path fluxc-processor --path plugins --path tests --path example/src --path example/build.gradle --path example/proguard-rules.pro --invert-paths
```

This is _not_ a destructive action. This module will be available in git history as well as in separate repository.

### CODE REVIEW

**Comment by wzieba** [comment]
@aforcier @malinajirka as participants of p1605009939037100-slack-C0QB79UV8 discussion - are you ok with reviewing this PR? Thanks in advance!

**Comment by malinajirka** [comment]
Tbh I'm not familiar enough with git to do a good review of this PR. I think we should ask someone from the Platform9 team. Wdyt?

I tried building and running fluxc and it works as expected. It seems all references of instaflux have been removed. 

I noticed that [the new repo](https://github.com/wordpress-mobile/InstaFlux) contains not just the `instaflux` folder but even all non-module files&folders - could you please elaborate what are the benefits of including those files? Thanks!

**Comment by wzieba** [comment]
> Tbh I'm not familiar enough with git to do a good review of this PR. I think we should ask someone from the Platform9 team. Wdyt?

Good idea, I'll add Platform9 to reviewers.

> I tried building and running fluxc and it works as expected. It seems all references of instaflux have been removed.

Thanks!

> I noticed that the new repo contains not just the instaflux folder but even all non-module files&folders - could you please elaborate what are the benefits of including those files? Thanks!

Many of those non-modules files&folders are needed to compile `instaflux` - things like projects `build.gradle` and `settings.gradle`. `example` and `.configure-files` directories contains samples secrets setup. Maybe I could not add `.buildkite` and `.circleci` - those might be indeed not needed.

**Comment by wzieba** [comment]
Sorry everyone for reviewers headache 🙇‍♂️  - assigning Owl team now.

**Comment by oguzkocer** [comment]
Since this is not a high priority PR, I can't get to it for a couple days. However, if it's still not reviewed in the next few days (next week the latest) I'd be happy to review it. I'd like to first finish the important part of a high priority project I am working on right now. Sorry about that!

**Comment by wzieba** [comment]
No problem - I agree it's not a high priority one. Thanks for heads up!

**Comment by shiki** [comment]
@wzieba Just out of curiosity, were you able to measure how much this improves the build time?

**Comment by wzieba** [comment]
I haven't done any build time metrics here but I believe the difference wouldn't be significant. On CI probably not noticeable as for tasks we specify module (e.g. [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/.circleci/config.yml#L43)) so Instaflux is untouched in those cases. 

I made this change rather for improving working with IDE (I thought about it every time I've seen "Indexing Instaflux" there), project-wide tasks like `ktlintFormat` and reduce any possible overhead in the future with bumping dependencies or SDK.

So can't say about metrics but I believe it's better to have it in a separate repository if it's not used 🙂.

**Review by oguzkocer — APPROVED** [review]
The paths used to generate the git commits for the new repository seems to include a few extras, but I don't think having extra commits is a problem. If we want to maintain that repository, there is some cleanup work to do which I see @wzieba already started. I don't think the project will be used much, so it might not worth spending too much time on it. Actually, I would have been totally fine to merge this PR without that new repository, but thank you for going the extra mile @wzieba 🙇‍♂️ 

One note though, I think the new repository should be public. Was that maybe an oversight or was it a deliberate decision? It's moving from a public repository and I can't think of a reason for it to be private.

**Comment by wzieba** [comment]
Thanks @oguzkocer !

> One note though, I think the new repository should be public. Was that maybe an oversight or was it a deliberate decision? It's moving from a public repository and I can't think of a reason for it to be private.

True, there's no reason making it private. I just made it public.

**Pull request merged**
