### PR TITLE
Android 13 Migration: Update compileSdkVersion to 33

### PR DESCRIPTION
**Pull request by ravishanker**
Update compileSdkVersion to 33

_Internal project thread: pbArwn-5IN-p2_

To test

- Checkout this branch
- Use this branch through WP (uncomment locaFluxCPath in local-builds.gradle)
- Log out if already logged in
- Try out login and various flows
- Ensure, no issues or crashes

### CODE REVIEW

**Comment by ravishanker** [comment]
👋 @irfano - What branch this should target?

**Comment by irfano** [comment]
> 👋 @irfano - What branch this should targe?

👋If the migration requires multiple PRs, a new parent branch for the migration could be used. If the required changes are not too much, single PR targeting `trunk` can be enough.

**Review by irfano — COMMENTED** [review]
There are no errors after the upgrade, but there are some new warnings.
However, even before upgrading to API 33, there were already many warnings. I don't think we should fix them all in this PR. 
We can try to solve the new warnings here, but I'm not sure if we should do that. `allWarningsAsErrors` is not enabled in FluxC (although it's enabled on WPAndroid), so maybe we can skip resolving all of these warnings.
I would also like to hear @ParaskP7 opinion.

**Comment by ParaskP7** [comment]
👋 @ravishanker @irfano !

Yes, you're right, `allWarningsAsErrors` is only enabled (so far) on the WPAndroid and WCAndroid clients, but none of the libraries are having that enabled (just yet), with a couple of exceptions (like Aztec and Utils).

Thus, and unless you would like to do a diff of the previous vs new warnings, and then try to fix them, ignoring them is (kind of) okay.

PS: The same comment applies to all the other such library upgrades you are currently working on, you don't need to be blocked by me. As long as you've tested the upgrade and gave your 👍 on it, feel free to merge it.

**Review by irfano — APPROVED** [review]
LGTM! I did a simple smoke test and haven't encountered any issues. There are some new warnings, but I have yet to find any critical warnings that must be resolved.
@ravishanker, I don't see any blocker for merging this, but I have seen the `[PR] Not Ready for Merge` label. Feel free to merge it if there is no blocker.

**Pull request merged**
