### PR TITLE
Update okhttp version

### LINKED ISSUE #919: Resolve self-hosted SSL + OkHttp 3.9.1+ issue
It looks like OkHttp `3.9.1` or later breaks support for self-hosted SSL sites (at least, it does for our shared test site). We're currently on `3.9.0` for this reason - if/when we want to update `OkHttp`, we'll need to understand and resolve the issue.

See https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/918 for some background.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #919 

In this PR I'm updating OkHTTP version and implementing a fix that enables logging in with a self-signed certificate once it's been approved by the user. This should fix the issue linked in this PR. Let me know if this approach makes sense to you. I was inspired by the newer implementation of the `MemorizingTrustManager`. It seems that adding the `MemorizingHostnameVerifier` does the trick. 

This could be tested using the self-signed site from tests.properties using [this WP Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/13291).

### CODE REVIEW

**Comment by aforcier** [comment]
🎉 thanks for taking this on @planarvoid ! I haven't tested WPAndroid yet, but I confirmed that I can log in and make requests to a self-signed SSL test site from the example app (and that I can't if I just update okhttp without your changes).

However the connected tests that use the self-signed ssl site (`ReleaseStack_ReactNativeWPAPIRequestTest#testAuthenticatedCallToSelfSignedSslSite` and ` ReleaseStack_SiteTestXMLRPC#testXMLRPCSelfSignedSSLFetchSites`) are failing for me, presumably some extra config is needed for the debug/test network stack to work properly?

**Comment by planarvoid** [comment]
good catch @aforcier ! I've only added the hostname verifier to the debug okhttp builder, I've added it to release builder as well in e1d277c so all should be good now 👍

**Comment by aforcier** [comment]
Working well now @planarvoid 👍 This seems good to go, though getting one more person to test/run the connected tests would probably be a good idea since updating okhttp is such a deep change.

**Review by malinajirka — APPROVED** [review]
Thanks @planarvoid! I've tested the changes on 4 different android version and it all works as expected. Great job!

Feel free to merge this PR and create a new tag.

**Pull request merged**
