### PR TITLE
FluxC: Fix `ReleaseStack_ActivityLogTestJetpack` connected tests 

### PR DESCRIPTION
**Pull request by ashiagr**
This PR 
- Addresses the original failing connected test (`testFetchActivitiesActivityTypeFilter()`) reported in the Slack thread: p1654776866818809-slack-C02QANACA by updating `jp-complete` site account creds in mobile secrets and CI. I used instructions from the field guide: PCYsg-kHN-p2 to update the creds.

- Makes another one (`testFetchRewindableActivities()`) more robust as suggested here: p1655378738625199/1654776866.818809-slack-C02QANACA

However, all connected tests do not pass so this PR is marked `draft` to discuss any potential issues or consider those failing tests as flaky.

Out of the [four failing tests in the last pass](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/7437/workflows/7a1cf3c6-e4c6-46e2-933c-6a8174703465/jobs/18998), three are flaky but one is not.

`testAutoSaveModifiedDateIsDifferentThanPostModifiedDate`
 `testAutoSaveScheduledPost`   (flaky)
`testFetchSitesWithTwoFilters` (flaky)  
`testFetchSitesWithAtomicFilter` (flaky)

(P.S. Two tests are repeated in the screenshot)

failed tests

The non-flaky failing test `testAutoSaveModifiedDateIsDifferentThanPostModifiedDate` pass in my local environment: 

testAutoSaveModifiedDateIsDifferentThanPostModifiedDate

This test did not fail in the [previous CI pass](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-FluxC-Android/7432/workflows/dea609df-17e0-4919-a0ce-01ca7c7f7a30/jobs/18993) which makes me think `testAutoSaveModifiedDateIsDifferentThanPostModifiedDate` might be flaky as well as it passes on my local environment or the updated creds files are not encrypted correctly in https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/0a031c9fdbe53ca225058d4dcc94aad748c19b29. 

failed_tests_prev_pass

I welcome all suggestions that can help make all connected tests pass. Thank you!

### CODE REVIEW

**Comment by ashiagr** [comment]
👋 @oguzkocer 

As you're aware of the `FluxC` creds files handling and were involved in the recent changes to the process, we needed your help to pass this PR. 

To provide you with some context, we needed to change the password for an existing account (see p1654776866818809-slack-C02QANACA) to fix a failing test. For that, I followed the steps from the field guide: PCYsg-kHN-p2. The `Gradle` tasks to apply and update configuration initially did not succeed in my `FluxC` repo so I git cloned a fresh copy, performed the steps and committed the changed files in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2441/commits/0a031c9fdbe53ca225058d4dcc94aad748c19b29

The failing connected test passed but another test failed which was not marked flaky (see PR description). @ParaskP7 and I paired today but could not find anything odd with our changes.

We need to verify that

- the files in commit https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2441/commits/0a031c9fdbe53ca225058d4dcc94aad748c19b29 are correctly changed.
- `testAutoSaveModifiedDateIsDifferentThanPostModifiedDate` might be flaky as it passes locally.

Can you help us in any way?

**Comment by oguzkocer** [comment]
Hi there @ashiagr 👋 

> the files in commit https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/0a031c9fdbe53ca225058d4dcc94aad748c19b29 are correctly changed.

The changeset looks correct to me. I am getting a different encrypted file if I run the `updateConfiguration` command, but I _think_ that's expected.

When I apply the configuration, I can see the test properties in `example/properties/tests.properties`, so that looks good 👍 Also, if there was an issue with the configuration, I'd expect it to happen while it's being applied and not during the test.

> `testAutoSaveModifiedDateIsDifferentThanPostModifiedDate` might be flaky as it passes locally.

I unfortunately do not have any prior knowledge about this test or the other ones mentioned in the PR description.

When I made a similar update before, I had to make sure the test site was setup correctly for the tests or the test details were updated to reflect the new setup. You can take a look at #2391 for an example.

Having said that, if you'd like me to investigate a particular issue, please let me know. I doubt I'll find anything more than you and @ParaskP7 did, but I don't mind trying.

**Comment by ParaskP7** [comment]
👋 @ashiagr !

> Having said that, if you'd like me to investigate a particular issue, please let me know. I doubt I'll find anything more than you and @ParaskP7 did, but I don't mind trying.

Thank you for checking us on that @oguzkocer , much appreciated! 🙇 

@ashiagr , maybe it is worth merging that change to `trunk` and see whether this single non-flaky `testAutoSaveModifiedDateIsDifferentThanPostModifiedDate()` test is actually flaky or not.

Maybe it just is and as such there will be nothing for us to fix any further. Or maybe, it will start failing consistently, just like the `testFetchActivitiesActivityTypeFilter()` test that you fixed with a password reset. At which point, we will investigate it further and try to resolve it too. No matter, I think this PR is a progress and we can merge it, in the worse case scenario we will just have `FluxC` keep failing with a specific test, just as it happens at the moment anyway. Wdyt? 🤔

**Comment by ashiagr** [comment]
> The changeset looks correct to me.

Thanks for confirming it, @oguzkocer! 

 > I think this PR is a progress and we can merge it, in the worse case scenario we will just have FluxC keep failing with a specific test, just as it happens at the moment anyway. Wdyt? 🤔

I have similar thoughts, @ParaskP7. I triggered tests one last time but I'll merge the PR whatever be the results since it fixes the originally reported issue. We can further investigate if tests still fail on `trunk`.

**Pull request merged**
