### PR TITLE
Fix unit tests execution above JDK 11

### LINKED ISSUE #2540: Fix unit tests for JDK > 11
#### Environment 
M1

JDK:
> openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode)

#### Reproduction
Running `./gradlew testDebug` results in failing tests

#### Reason
ByteBuddy from Mockito. 

#### Solution

Bumping `mockito` to 4.8.0 should fix the issue. We should as well bump `mockito-kotlin` to newest stable release (`4.0.0`).

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #2540 
X: https://github.com/Automattic/android-dependency-catalog/pull/7

### Description

This PR fixes failing unit test execution on JDKs higher than 11 by updating `mockito-core` version. With this update, we needed to drop support for nhaarman's `mockito-kotlin` in favor of mockito's `mockito-kotlin`.

### Review instructions

Please review this PR commit by commit. Changes in commit marked with "automated" are changes made by IDE's find&replace + optimize imports tools. Those changes might not be worth reviewing.

### Test instructions

1. Firstly, make sure you can reproduce the issue. Install any JDK above 11 and update `JAVA_HOME` (if you use terminal) or settings in Android Studio (if you use AS). Hint: Android Studio Eel has embedded JDK version 17
2. Checkout `trunk`
3. Run unit tests
4. **Assert that unit tests fail** (`Mockito cannot mock this class (...)`)
5. Checkout `issue/2540_fix_unit_tests_execution_above_jdk11` branch
6. Run unit tests again
7. **Assert that unit tests pass**

### Merging instructions

Please do not merge this PR until a new version of the dependency catalog is released, and the tag in this PR is updated.

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]
Thank you for addressing this issue @wzieba! I've ran the tests with JDK 18 in `trunk` to verify the failures and confirmed that this branch fixed them.

**Comment by wzieba** [comment]
Thanks @oguzkocer ! I've updated the version of the catalog to the newly released `1.4.0`. Merging.

**Comment by ParaskP7** [comment]
👋 @wzieba !

FYI: I am still seeing `com.nhaarman.xzy` related imports for the `JitmRestClientTest.kt` test and `org.wordpress.android.fluxc.network.rest.wpcom.jitm` package.

PS: Thanks for this work you did! 🥇

**Comment by wzieba** [comment]
hi @ParaskP7 👋 , thanks! I should've merged the recent `trunk` before merging this PR. I'm preparing a fix.

**Pull request merged**
