### PR TITLE
Remove CircleCI build status shield from `README.md`

### PR DESCRIPTION
**Pull request by mokagio**
We no longer use CircleCI.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
Good catch @mokagio ! 💯 

FYI: I did another quick search on any reference on the `CircleCI` keyword in this repo and found out that this `ReleaseStack_EncryptedLogTest` is being ignored because of CircleCI. 

Suggestion (💡): Maybe we can remove this `@Ignore` annotation (and its import) from this test, in this PR, and see if everything is okay with this test passes on Buildkite. This might be a potential quick win, and worse case, we'll revert that. Wdyt? 🤔

PS: Having said the above, note the fact that for some time now the `Connected Tests` job is not required for `FluxC` PRs to be merged. This is because we have some tests still failing there that need to be fixed before we can re-enabled that check. Thus, we will need to check if that specific `ReleaseStack_EncryptedLogTest` test passes in Firebase manually.

**Comment by mokagio** [comment]
@ParaskP7 I like your suggestion 👍 It seems like a good occasion to bring the test coverage quality back to a higher level.

However, I have no experience with Firebase Test Lab and, as much as this might be a quick win, it wouldn't be quick _for me_ to look into 😳 😓 I love learning new things, but I'm catching up on various projects at the moment and can't fit this it. Sorry for the digression, I just wanted to explain why I wasn't going to action your suggestion myself/timely.

I'm going to merge this PR in the meantime.

**Comment by ParaskP7** [comment]
> @ParaskP7 I like your suggestion 👍 It seems like a good occasion to bring the test coverage quality back to a higher level.

👍 

> However, I have no experience with Firebase Test Lab and, as much as this might be a quick win, it wouldn't be quick for me to look into 😳 😓 I love learning new things, but I'm catching up on various projects at the moment and can't fit this it. Sorry for the digression, I just wanted to explain why I wasn't going to action your suggestion myself/timely.

Of course @mokagio and please don't worry about it, it's just a suggestion after all, something I wouldn't even give to you if it wasn't for your PR. ❤️ 

I'll save this suggestion in my TODO list and apply this simple removal myself on a separate PR, probably next week. I'll mention you in the PR so you can check its progress in case you get curious. 💯 

> I'm going to merge this PR in the meantime.

🚀

**Comment by ParaskP7** [comment]
👋 @mokagio !

> I'll save this suggestion in my TODO list and apply this simple removal myself on a separate PR, probably next week. I'll mention you in the PR so you can check its progress in case you get curious. 💯

FYI: [The PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2641) has been now created. 🤞

**Pull request merged**
